### PR TITLE
fix: Log error message if malformed JSON file found

### LINKED ISSUE #7637: [BUG]: plotly.js DevTools crashes if malformed JSON file exists in mocks folder
### Description

Running `npm start` starts up plotly.js DevTools. If a malformed JSON exists in the mocks folder (**test/image/mocks)**, this process will crash and the dev server won't start. The script should be updated to handle this situation.

### Steps to reproduce

- Add an empty JSON file to the mocks folder:
  ```sh
  touch test/image/mocks/empty_file.json
  ```
- Run `npm start`
- Note that the process crashes
  ```sh
  $ npm start

  > plotly.js@3.3.0 start
  > node devtools/test_dashboard/server.mjs

  undefined:1


  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at file:///home/cam/Development/plotly/plotly.js/devtools/dashboard_utilities.mjs:43:31
      at Array.map (<anonymous>)
      at createMocksList (file:///home/cam/Development/plotly/plotly.js/devtools/dashboard_utilities.mjs:42:33)
      at async file:///home/cam/Development/plotly/plotly.js/devtools/test_dashboard/server.mjs:19:1

  Node.js v18.20.8
  ```

### PR DESCRIPTION
**Pull request by camdecoster**
### Description

Add logic to catch errors when mocks are loaded in plotly.js DevTools and log a message.

Closes #7637.

### Changes

- Add error handling logic

### Testing

- Be on master
- Add an empty JSON file to the mocks folder:
  ```sh
  touch test/image/mocks/empty_file.json
  ```
- Run `npm start`
- Note that the process crashes
- Switch to this branch
- Run `npm start`
- Note that the process doesn't crash and an error message is logged

### CODE REVIEW

File: devtools/dashboard_utilities.mjs [hunk 1]
```diff
@@ -40,20 +40,24 @@ export function createMocksList(files) {
...
-            file: filename,
-            keywords: types.join(', ')
-        };
+            return {
+                name: filename.slice(0, -5),
+                file: filename,
+                keywords: types.join(', ')
+            };
+        } catch {
+            console.log(`Couldn't parse ${file.name} as JSON. Excluding from mocks list.`);
```
Comment (emilykl) [inline devtools/dashboard_utilities.mjs]: @camdecoster Could we still surface the stack trace here, in case the code inside `try` fails in an unexpected way due to something other than the call to `JSON.parse()`?

Either that, or put _only_ the `JSON.parse()` call inside the `try`.

Comment (camdecoster) [reply devtools/dashboard_utilities.mjs]: I added more specific error handling.
