### PR TITLE
Fix issue where styles weren't reset when re-using SVGs in colorbar

### LINKED ISSUE #5161: Lowest colormap color is set to white when chart type is changed to contour
When updating chart data and setting type to "contour", the lowest color in the colormap is always set to white instead of the right color.

This is a reproduction on codepen: https://codepen.io/fredx87/pen/YzqdJZz

If I use `Plotly.react` the colorbar is wrong, if I redraw the chart using `Plotly.newPlot` the colorbar is correct.

### PR DESCRIPTION
**Pull request by anaplian**
Fixes #5161

### CODE REVIEW

**Comment by archmoj** [comment]
Good catch!
[Before](https://codepen.io/MojtabaSamimi/pen/ExyyeWz) vs [After](https://codepen.io/MojtabaSamimi/pen/gOMMdmm).

**Comment by archmoj** [comment]
@anaplian to lock this issue, would you please add a test possibly to the end of this block?
https://github.com/plotly/plotly.js/blob/7f6650bac64c3987f59dd09aa5ed26195ea77b58/test/jasmine/tests/colorbar_test.js#L74

To run the `colorbar` test locally you could simply use
```
npm run test-jasmine -- colorbar
```

Thanks!

**Comment by anaplian** [comment]
@archmoj Thanks! I have added a test. Let me know what you think :smile:

File: test/jasmine/tests/colorbar_test.js [hunk 1]
```diff
@@ -524,5 +524,44 @@ describe('Test colorbar:', function() {
             .catch(failTest)
             .then(done);
         });
+
+        it('creates the same colorbars attributes in newPlot and react', function(done) {
+            var z = [[1, 10], [100, 1000]];
+
+            var expectedAttrs = [];
+            var actualAttrs = [];
+
```
Comment (archmoj) [inline test/jasmine/tests/colorbar_test.js:533]: The test looks great.
Non-blocking, but maybe you could add a getter function to avoid duplication:
Something like:
```js
function pushItemsTo(a) {
    var colorbars = d3.select(gd).selectAll('.colorbar');
    colorbars.selectAll('.cbfill').each(function() {
        var attrsForElem = {};
        for(var i = 0; i < this.attributes.length; i++) {
            var attr = this.attributes.item(i);
            attrsForElem[attr.name] = attr.value;
        }
        a.push(attrsForElem);
    });
}

Plotly.newPlot(gd, [{type: 'contour', z: z}])
.then(function() {
    pushItemsTo(expectedAttrs);

    return Plotly.newPlot(gd, [{type: 'heatmap', z: z}])
    .then(function() {
        return Plotly.react(gd, [{type: 'contour', z: z}]);
    });
})
.then(function() {
    pushItemsTo(actualAttrs);

    expect(actualAttrs).toEqual(expectedAttrs);
})
```

Comment (anaplian) [reply test/jasmine/tests/colorbar_test.js]: Done :slightly_smiling_face:

**Comment by archmoj** [comment]
Nicely done!
Thanks very much @anaplian :1st_place_medal: 
:dancer:
