### PR TITLE
Fix hover label in stacked bars

### LINKED ISSUE #1157: stacked bar chart hover labels showing cumulative values since 1.20
hi.

stacked bar chart hover labels used to show individual values
since 1.20 they start showing cumulative ones
could this be reverted or could an option be added to choose what is shown?
thanks

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #1157

### CODE REVIEW

File: src/traces/bar/hover.js [hunk 1]
```diff
@@ -65,17 +65,18 @@ module.exports = function hoverPoints(pointData, xval, yval, hovermode) {
     if(Color.opacity(mc)) pointData.color = mc;
     else if(Color.opacity(mlc) && mlw) pointData.color = mlc;
 
+    var size = (trace.base) ? di.b + di.s : di.s;
```
Comment (n-riesco) [inline src/traces/bar/hover.js]: The bars of traces that set `base` have their `di.b` set accordingly and are excluded from stacking. The size of these bars is computed as `di.b + di.s`.

The bars of traces that don't set `base` have their `di.b` set to 0, unless they are stacked, in which case, the stacking algorithm sets `di.b`. For these bars, the bar size is `di.s`; no need to add `di.b` (either because it'd be 0, or because it'd be something that the stacking algorithm has set to stack the bars).

Comment (etpinard) [inline src/traces/bar/hover.js]: Ok. I think you got this right.

For reference, here's the non-stacked case under `base` restyle:

![gifrecord_2016-11-17_133959]
(https://cloud.githubusercontent.com/assets/6675409/20402731/eb1ee9a6-accb-11e6-8e7a-c06c88ccbda5.gif)

Perhaps we could set a special flag in the stacked bar calcdata traces [here](https://github.com/plotly/plotly.js/blob/564f661cd2831cb3e97a1eaec1d0f8505bedd2fb/src/traces/bar/set_positions.js#L96) instead of relying on the fact that all stacked bars have falsy `trace.base`. Or maybe adding a few test cases will suffice.

**Comment by etpinard** [comment]
Thanks @n-riesco for the quick turnaround :beers:
