### PR TITLE
Fix unknown filename when exporting charts using new versions of Safari

### LINKED ISSUE #1227: Unknown filename when exporting charts (Safari)
Hi,

I've been using the "Export" feature to save charts as images and it's working mostly great! However, in Safari 10.0.1 (Mac OSX), the file is downloaded with the name "Unknown" without even an extension.

Here is an example: https://plot.ly/~bd_plotly/46

Could you please check this issue out?

Thank you very much!

### PR DESCRIPTION
**Pull request by archmoj**
Closes #1227.

Follow up for PR #5609 thanks to @rlreamy 

@plotly/plotly_js

### CODE REVIEW

File: test/jasmine/tests/download_test.js [hunk 1]
```diff
@@ -137,8 +137,8 @@ describe('Plotly.downloadImage', function() {
         })
         .then(done, done.fail);
     }, LONG_TIMEOUT_INTERVAL);
-
-    it('should produce right output in Safari', function(done) {
+/*
+    it('should produce right output in Old Safari', function(done) {
```
Comment (alexcjohnson) [inline test/jasmine/tests/download_test.js:141]: Do we really want to keep these commented-out tests around? Unless you want to try and mock `canUseSaveLink===false` - which I don't really think is worth it at this point - I'd just delete them.

**Review by alexcjohnson — APPROVED** [review]
💃 after doing something with the obsolete tests.

**Comment by nicolaskruchten** [comment]
✨  works for me on Safari 13.
