### PR TITLE
fix: React to config changes

### LINKED ISSUE #7551: Some configuration changes aren't reflected during calls to `Plotly.react`
### Description

Some configuration changes aren't reflected during calls to `Plotly.react`. This includes mode bar button title changes, icons, etc. Toggling display of the logo (among other config options) seems to force a full update that reflects all the config changes. This is discussed a bit [here](https://github.com/plotly/plotly.js/issues/6394#issuecomment-1348812123) in #6394.

### Steps to reproduce

- Be on master
- Launch Plotly DevTools
- Open mock **line_scatter** (other mocks could work, but I know this one does)
- Run the following snippet to update the mode bar buttons:
  ```js
  let toggle = true

  Plotly.react(
    gd,
    gd.data,
    gd.layout,
    {
      displaylogo: false,
      modeBarButtonsToAdd: [
        {
          name: 'custombutton',
          title: toggle ? 'Take PICTURE' : 'Record MOVIE',
          icon: toggle ? Plotly.Icons.camera : Plotly.Icons.movie,
          click: () => {}
        },
      ],
      modeBarButtonsToRemove: [
        "autoscale",
        "pan2d",
        "lasso2d",
        "resetScale2d",
        "select2d",
        "toImage",
        "zoom",
        "zoomIn2d",
        "zoomOut2d"
      ]
    }
  )
  ```
- Run this other snippet to update the label of the custom button:
  ```js
  toggle = false

  Plotly.react(
    gd,
    gd.data,
    gd.layout,
    {
      displaylogo: false,
      modeBarButtonsToAdd: [
        {
          name: 'custombutton',
          title: toggle ? 'Take PICTURE' : 'Record MOVIE',
          icon: toggle ? Plotly.Icons.camera : Plotly.Icons.movie,
          click: () => {}
        },
      ],
      modeBarButtonsToRemove: [
        "autoscale",
        "pan2d",
        "lasso2d",
        "resetScale2d",
        "select2d",
        "toImage",
        "zoom",
        "zoomIn2d",
        "zoomOut2d"
      ]
    }
  )
  ```
- Note that the button title and icon have not updated

### Notes

- This issue was split off from #6394 as mentioned [here](https://github.com/plotly/plotly.js/issues/6394#issuecomment-3255860401)
- It appears that this issue was also written up downstream in cshaa/svelte-plotly.js#10

### PR DESCRIPTION
**Pull request by archmoj**
### Description

Use `newPlot` if config has changed instead of `_doPlot` inside `Plotly.react`.

Closes #7551.
Supersedes #6395.

### Changes

- Adds check to determine if `newPlot` should be used
- Updates tests per above change

### Testing

- Be on master
- Launch Plotly DevTools
- Open mock **line_scatter** (other mocks could work, but I know this one does)
- Run the following snippet to update the mode bar buttons:
  ```js
  let toggle = true

  Plotly.react(
    gd,
    gd.data,
    gd.layout,
    {
      displaylogo: false,
      modeBarButtonsToAdd: [
        {
          name: 'custombutton',
          title: toggle ? 'Take PICTURE' : 'Record MOVIE',
          icon: toggle ? Plotly.Icons.camera : Plotly.Icons.movie,
          click: () => {}
        },
      ],
      modeBarButtonsToRemove: [
        "autoscale",
        "pan2d",
        "lasso2d",
        "resetScale2d",
        "select2d",
        "toImage",
        "zoom",
        "zoomIn2d",
        "zoomOut2d"
      ]
    }
  )
  ```
- Run this other snippet to update the label of the custom button:
  ```js
  toggle = false

  Plotly.react(
    gd,
    gd.data,
    gd.layout,
    {
      displaylogo: false,
      modeBarButtonsToAdd: [
        {
          name: 'custombutton',
          title: toggle ? 'Take PICTURE' : 'Record MOVIE',
          icon: toggle ? Plotly.Icons.camera : Plotly.Icons.movie,
          click: () => {}
        },
      ],
      modeBarButtonsToRemove: [
        "autoscale",
        "pan2d",
        "lasso2d",
        "resetScale2d",
        "select2d",
        "toImage",
        "zoom",
        "zoomIn2d",
        "zoomOut2d"
      ]
    }
  )
  ```
- Note that the button title and icon have not updated
- Switch to this branch
- Reload the mock
- Run the two snippets again
- Note that the button title and icon have changed

### Notes

- This PR was originally created by @archmoj, but @camdecoster updated the OP with testing details
- Though this change fixes the issue with some config updates not being reflected in the new plot, it doesn't add the original config to the graph div like `gd.data` or `gd.layout`. For that reason, I don't think that this PR fixes the original issue in #6394 so I'm not going to close that issue once this merges.

### CODE REVIEW

**Review by camdecoster — COMMENTED** [review]
This seems okay, but before I approve could you please provide a description and some steps to reproduce the issue? Then I can test before/after changes and see the fix in action.

**Comment by emilykl** [comment]
~@camdecoster This is intended to address https://github.com/plotly/plotly.js/issues/6394, correct?~

Never mind, just saw your comment in the PR description. In that case, would it make sense to open another issue which can be closed by this PR?

**Review by emilykl — APPROVED** [review]
Looks reasonable to me.

**Comment by camdecoster** [comment]
> ~@camdecoster This is intended to address #6394, correct?~
> 
> Never mind, just saw your comment in the PR description. In that case, would it make sense to open another issue which can be closed by this PR?

Yes. I have a comment drafted about that, but never submitted it. :facepalm:

File: src/plot_api/plot_api.js [hunk 1]
```diff
@@ -2615,129 +2615,140 @@ function react(gd, data, layout, config) {
...
+        }
     }
 
-    return plotDone.then(function() {
-        gd.emit('plotly_react', {
-            data: data,
-            layout: layout
-        });
+    return plotDone.then(() => {
+        if (!configChanged) gd.emit('plotly_react', { config, data, layout });
```
Comment (emilykl) [inline src/plot_api/plot_api.js:2751]: @camdecoster Is there a reason we don't want to emit a `plotly_react` event if the config changed?

Comment (camdecoster) [reply src/plot_api/plot_api.js:2751]: It will emit twice for one call to `react` without that check. This is because we call `newPlot` and then `react` again after that, all within the first call to `react`.
