### PR TITLE
Fix small sizes of bar with base

### LINKED ISSUE #5057: Base attribute bug
I have tried to make simple timeline with the help of base attribute. Run into problem with low x values. If x is lower than 10000 ms, plot breaks as seen in example. With values higher than 10s, plot works as expected.  Possible bug, thanks for help or maybe explanation if i am doing something wrong. 

Codepen - https://codepen.io/kristi-n-krob-nek/pen/dyMoKNJ

Also tried to look for similar issue before posting, but found nothing close to this problem.

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5057.

@plotly/plotly_js

### CODE REVIEW

File: test/jasmine/tests/bar_test.js [hunk 1]
```diff
@@ -423,6 +423,33 @@ describe('Bar.calc', function() {
...
+            type: 'bar',
+            base: [0],
+            y: [2000],
+            x: ['A']
+        }], {});
+
+        var cd = gd.calcdata;
+        assertPointField(cd, 'b', [[0]]);
+        assertPointField(cd, 's', [[2000]]);
+    });
```
Comment (alexcjohnson) [inline test/jasmine/tests/bar_test.js:438]: Don't these tests need to explicitly specify date axis type?

Comment (archmoj) [reply test/jasmine/tests/bar_test.js:437]: Good catch. Fixed in https://github.com/plotly/plotly.js/pull/5061/commits/3e439e01428fb1a3d56aa45b7a51ed50a8dc6557.
