### PR TITLE
Make events work in jQuery no-conflict scopes [fixes #350]

### LINKED ISSUE #350: plotly.js breaks when jQuery is imported with no-conflict flag
https://cdn.plot.ly/plotly-latest.min.js line 31
Seems to be broken right now.

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz easy fix.

### CODE REVIEW

File: test/jasmine/tests/events_test.js [hunk 1]
```diff
@@ -192,4 +190,107 @@ describe('Events', function() {
         });
     });
 
+    describe('when jQuery.noConflict is set, ', function() {
+
+        beforeEach(function() {
+            $.noConflict();
```
Comment (etpinard) [inline test/jasmine/tests/events_test.js]: ref: https://api.jquery.com/jquery.noconflict/

**Comment by mdtusz** [comment]
Don't see anything wrong with that. 

:dancer:
