### PR TITLE
Bug fix waterfall hovermode closest decreasing values

### LINKED ISSUE #3776: Waterfall hovermode closest bug
In this pen https://codepen.io/nicolaskruchten/pen/EJoypE I have hovermode='closest' and hovering over the red bar doesn't show the hoverlabel: I have to hover over the empty space below it. (note: hovermode=closest is the default in Chart Studio now)

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #3776.
[Codepen After](https://codepen.io/MojtabaSamimi/pen/rbpvZo).

@plotly/plotly_js 
cc: @nicolaskruchten

### CODE REVIEW

File: src/traces/bar/hover.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ function hoverOnBars(pointData, xval, yval, hovermode) {
     var trace = cd[0].trace;
     var t = cd[0].t;
     var isClosest = (hovermode === 'closest');
+    var isWaterfall = (trace.type === 'waterfall');
```
Comment (etpinard) [inline src/traces/bar/hover.js]: Hmm. I guess it would be annoying to move this logic in `waterfall/hover.js`. :disappointed:

**Comment by etpinard** [comment]
Thanks for the fix and test :dancer:
