### PR TITLE
Fix stacked area hide show bug

### LINKED ISSUE #7660: [BUG]: filled area plots having trouble showing trace in correct position after hiding/showing traces
### Description

Filled area plots do not place trace in correct position after showing exclusively single trace and resetting plot to show all traces.

### Screenshots/Video

Image

### Steps to reproduce

- Go to https://plotly.com/javascript/filled-area-plots/#stacked-area-chart
- Double-click "trace 1" to show "trace 1" only
- Click "trace 1" again
- Now plot is empty
- Double click any trace to show all traces again

### Notes

Seems like "trace 1" is still plotted but without the necessary y-offset so it's hidden behind "trace 0"

### PR DESCRIPTION
**Pull request by emilykl**
Closes #7660 

Fixes issue where some traces in stacked area charts were not rendering their fill correctly after certain sequences of hide/show operations in the legend.

### Reproduce existing issue
1. Go to [this Codepen](https://codepen.io/pen?&prefill_data_id=0afc953b-17c5-4a87-8988-0a806ec15c7e) (from [the docs](https://plotly.com/javascript/filled-area-plots/#stacked-area-chart))
2. Follow the exact reproduction steps described in 7660:
  > - Double-click "trace 1" to show "trace 1" only
  > - Click "trace 1" again
  > - Now plot is empty
  > - Double click any trace to show all traces again
3. The orange trace should be missing a fill. This is the bug.
Screenshot 2025-12-08 at 5 47 23 PM

### Confirm that this PR fixes the issue
1. In the Codepen, replace the plotly.js script `src` with the build for this branch from the CI: https://output.circle-artifacts.com/output/job/c4caeb45-0a0b-4e23-97b6-ebb26b8561c8/artifacts/0/dist/plotly.js
2. Repeat the steps under (2) above
3. All trace fills should render normally.
Screenshot 2025-12-08 at 5 49 23 PM

### CODE REVIEW

File: src/traces/scatter/plot.js [hunk 1]
```diff
@@ -83,6 +83,11 @@ function createFills(gd, traceJoin, plotinfo) {
...
         var trace = d[0].trace;
 
+        // Clear any existing fill element references to ensure clean state
+        // This prevents stale references when fill configuration changes
+        trace._ownFill = null;
+        trace._nextFill = null;
+
         var fillData = [];
         if(trace._ownfill) fillData.push('_ownFill');
         if(trace._nexttrace) fillData.push('_nextFill');
```
Comment (camdecoster) [inline src/traces/scatter/plot.js]: Since you're making `_ownFill` and `_nextFill` null, the `if` checks will always fail. So, let's delete them.
```suggestion
        // Clear any existing fill element references to ensure clean state
        // This prevents stale references when fill configuration changes
        trace._ownFill = null;
        trace._nextFill = null;

        var fillData = [];
```

**Review by camdecoster — APPROVED** [review]

File: src/traces/scatter/plot.js (hunk 1 above)
Comment (emilykl) [reply src/traces/scatter/plot.js]: @camdecoster Tragically, `_ownFill` and `_ownfill`, as well as `_nextFill` and `_nexttrace`, are separate variables. 🙃

Comment (camdecoster) [reply src/traces/scatter/plot.js]: Ah, fair enough. I have words about this, but I won't include them here publicly.

**Comment by archmoj** [comment]
Thank you @emilykl for the fix.
The PR is missing a draftlog.
Other than that it looks good :dancer:

**Comment by emilykl** [comment]
@camdecoster I feel more confident about this fix now.

After reviewing the code, I'm satisfied that `trace._ownFill` and `trace._nextFill` are only intended to be used as temporary variables within the context of the `createFills()` function, and it's safe to reset them to `null` at the start of the function.

I think that lines 94-96 in the "before" code were intended to reset these to null as part of the D3 `.exit()` call; but I assume the bug manifested because `.exit()` is not always called on the `fillJoin` object, perhaps when the trace is not visible.

**Comment by maon-fp** [comment]
Thank you!
