### PR TITLE
Fix Plotly.download using graph id as 1st argument

### LINKED ISSUE #2930: TypeError: Cannot create property '_snapshotInProgress' on string 'plot'
This is my first post on here, so apologies if I have missed something ...

I'm getting a type error when using Plotly.downloadImage(). According to the docs [here](https://plot.ly/javascript/plotlyjs-function-reference/#common-parameters):

> The first argument to each function on this page is a reference to this element, and it can be either a DOM node, i.e. the output of document.getElementById(), or a string, in which case it will be treated as the id of the div.

But looking at /src/snapshot/download.js, it looks like passing the string (the id of the div) shouldn't work as the method doesn't look like it tries to find the DOM element from the passed string.... I've created a simplified CodePen that replicates the issue: https://codepen.io/DrRochy/pen/LJYbja

So, it seems to work correctly if you pass the object, but not when you just pass the string.

What's really weird is I am sure I have passed the id of the div element and this has worked, so I am very baffled how!

### PR DESCRIPTION
**Pull request by etpinard**
fixes #2930

cc @alexcjohnson

### CODE REVIEW

File: src/snapshot/download.js [hunk 1]
```diff
@@ -43,19 +45,19 @@ function downloadImage(gd, opts) {
             reject(new Error('Sorry IE does not support downloading from canvas. Try {format:\'svg\'} instead.'));
         }
 
-        gd._snapshotInProgress = true;
+        _gd._snapshotInProgress = true;
```
Comment (alexcjohnson) [inline src/snapshot/download.js]: Won't this fail for the plain object case (`_gd === undefined`)?

Comment (etpinard) [reply src/snapshot/download.js]: Good eye. This made me realize `Plotly.download` with figure objects as first argument was also broken. Fixed and :lock: ed in -> https://github.com/plotly/plotly.js/pull/2931/commits/a5af83c0275a6ae82c4b3cb9377982cc24cf268b

**Comment by alexcjohnson** [comment]
💃
