### PR TITLE
Z exponent fix

### LINKED ISSUE #2420: Contour plot "undefined" label when z >= 10 million
When contour z-points are greater than 10 million then the tooltip value is suffixed with "undefined". 

The suffix should be B or a multiple of 10M or it should render with an exponent. It should also be implemented for even larger values (1e8+).
```
var data = [ {
    z: [
        [1e6, 5e6, 1e7, 1.5e7],
        [1.2e6, 5.6e6, 1.1e7, 1.6e7]
    ], type: 'contour'
}];
Plotly.newPlot('myDiv', data);
```
undefined

### PR DESCRIPTION
**Pull request by alexcjohnson**
Fixes #2420 - #2106 improved formatting here but broke the default behavior for z values that need exponents. Fortunately the fix was a one-liner.

cc @etpinard

### CODE REVIEW

File: src/plots/cartesian/axes.js [hunk 1]
```diff
@@ -1528,7 +1528,7 @@ function numFormat(v, ax, fmtoverride, hover) {
     if(hover) {
         // make a dummy axis obj to get the auto rounding and exponent
         var ah = {
-            exponentformat: ax.exponentformat,
+            exponentformat: exponentFormat,
```
Comment (etpinard) [inline src/plots/cartesian/axes.js]: Nice catch :fishing_pole_and_fish:

File: test/jasmine/tests/hover_label_test.js [hunk 2]
```diff
@@ -550,6 +549,45 @@ describe('hover info', function() {
...
+            })
+            .then(function() {
+                [
+                    [expFmt(MINUS_SIGN + '1.234568', 23), MINUS_SIGN + '10B', MINUS_SIGN + '10k'],
+                    [MINUS_SIGN + '0.01', MINUS_SIGN + '10n', '0'],
+                    [expFmt('1.234568', -23), '10n', '0.01'],
+                    ['123.4568', '12.34568B', expFmt('1', 23)]
+                ]
+                .forEach(function(row, y) {
+                    row.forEach(function(zVal, x) {
```
Comment (etpinard) [inline test/jasmine/tests/hover_label_test.js]: :sparkles: test! Why create 12 test case when we can loop over 12 bricks!

**Comment by etpinard** [comment]
:dancer: nicely done
