### PR TITLE
Fix hover label exponents

### LINKED ISSUE #755: Hover label incorrect when number is very small (or large?)
**Live example**: http://codepen.io/rsreusser/pen/JKLGOL?editors=0010
(change min, max to see effect on when labels displayed correctly. I haven't figured out the pattern yet.)

**Expected behavior**: very small values show a hover label that represents the value. Shows scientific notation if beyond meaningful suffixes.

**Observed behavior**: Depending on the overall magnitudes involved, SI suffixes often just go missing. Which wouldn't be a big deal except for the fact that `1` when it should read `1n` is actually incorrect.

See SI prefixes here: http://www.npl.co.uk/reference/measurement-units/si-prefixes/

### PR DESCRIPTION
**Pull request by rreusser**
This PR fixes #755 and #1711. After a bit of digging:

**The problem**: Hover labels are sometimes wrong by arbitrarily gigantic orders of magnitude, which is bad. Hover labels piggyback on `Axes.tickText`, which sometimes hides exponents and just shows 1/2/5 values. That's *always* invalid for hover labels since their exponent is not shown elsewhere as it is for axes.

**The solution**: whenever `'hover'` is passed to `tickText`, this PR prevents it from making any automated decision about whether to hide the exponent, instead just obeying the axis formatting.

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Looks good to me. I could imagine with `showexponent: 'none'` wanting the hover labels to have no exponents either - but that's a weird case and I could equally imagine wanting the exponents *only* on hover in that case. If you want that kind of control you can make your own hover text :)

This whole system of `formatLinear`/`formatLog`/`numFormat` is a bit of a palimpsest at this point and probably should be completely refactored... but for now this is great.

I took the liberty of merging #1930 first, so you can fix these tests 🎉  and then 💃

**Comment by rreusser** [comment]
Haha good word. Yeah, the logic was about a 6/10 for subtle and intricate, so I was a bit worried I'd miss some cases. As is often the case then, I focused mainly on fixing the bug while adding and modifying as little as possible. I don't *quite* understand the above comment about `showexponent:  'none'` (like `0.0000000000000000112` then?) but seems like the top priority is that they're *not wrong*.

File: src/plots/cartesian/axes.js [hunk 1]
```diff
@@ -1346,10 +1350,18 @@ function formatCategory(ax, out) {
...
-    // ONLY tick to get an exponent (first or last)
-    if(ax.showexponent === 'all' && Math.abs(out.x / ax.dtick) < 1e-6) {
+    if(hideexp === 'never') {
+        // If this is a hover label, then we must *never* hide the exponent
+        // for the sake of display, which could give the wrong value by
+        // potentially many orders of magnitude. If hideexp was 'never', then
+        // it's now succeeded by preventing the other condition from automating
+        // this choice. Thus we can unset it so that the axis formatting takes
+        // precedence.
+        hideexp = '';
```
Comment (etpinard) [inline src/plots/cartesian/axes.js]: Thanks for the :books: @rreusser

**Comment by etpinard** [comment]
Very nice PR @rreusser thanks for doing this :tada: 

:hocho:'ing two issues in ~10 new LOCs is amazing!

**Comment by etpinard** [comment]
@rreusser this PR breaks [this](https://github.com/plotly/plotly.js/blob/4825f8ee0a6d3372c59c1fa6bcac390fccef7a1d/test/jasmine/tests/gl_plot_interact_test.js#L89) gl3d hover label test. CI :white_check_mark: as this particular test is skipped on CI. 

Can you make sure `npm run test-jasmine -- gl_plot_interact` passes?

**Comment by rreusser** [comment]
Sure. En route to meeting with Alex today so will fix during the flight, along with the final trace naming issue.
