### PR TITLE
Layer fix

### LINKED ISSUE #2110: Plotly shape always drawn under the trace when the plot type is pie
Code reference:
https://codepen.io/dipan66/pen/dVEXOy

In this, we are trying to draw a gauge chart by drawing a needle shape over a pie. The needle is always being drawn below the trace, though the layer attribute is set to "above". Need help / thoughts on how we can go about and get the needle shape to be drawn above the pie. 

Se are using Plotly.js v1.25.0

### PR DESCRIPTION
**Pull request by alexcjohnson**
fixes #2110 and #2119 
- put `layer-above` at the bottom of `toppaper` so shapes (and images) in this layer end up above *all* trace types
- put `updatemenus` into their own layer - `menulayer`, naturally, because the real reason they need to be on top is that they contain hidden elements that, whenever and wherever they are shown, need to take precedence over everything else.

### CODE REVIEW

File: src/components/shapes/draw.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ function draw(gd) {
 function drawOne(gd, index) {
     // remove the existing shape if there is one.
     // because indices can change, we need to look in all shape layers
-    gd._fullLayout._paper
+    gd._fullLayout._paperdiv
```
Comment (alexcjohnson) [inline src/components/shapes/draw.js]: Really we should just move shapes (and annotations for that matter) to the standard d3 update pattern like images already use (and which did not require this kind of change to adapt to the changed layering)... but that's a bigger project than I had an appetite for right now!

File: src/components/updatemenus/draw.js [hunk 2]
```diff
@@ -54,7 +54,7 @@ module.exports = function draw(gd) {
      */
 
     // draw update menu container
-    var menus = fullLayout._infolayer
+    var menus = fullLayout._menulayer
```
Comment (etpinard) [inline src/components/updatemenus/draw.js]: Ha I guess that does it. I first thought about splitting the updatemenu buttons from their header `<g>` i.e. the header would have remained in `<g infolayer>` and the buttons moved to `<g menulayer>`.

Can anyone think of a situation where one would want to place an updatemenu below other `<g infolayer>` features?

File: src/components/shapes/draw.js (hunk 1 above)
Comment (etpinard) [reply src/components/shapes/draw.js]: > but that's a bigger project than I had an appetite for right now!

Fixing two :beetle: in one PR, but hungry for more :hamburger:

File: src/components/updatemenus/draw.js (hunk 2 above)
Comment (alexcjohnson) [reply src/components/updatemenus/draw.js]: I can't see when you'd want the updatemenu below anything else, but I guess it could be useful to separate `<g menulayer>` itself into two pieces, so that regardless of the order you draw the menus, when they open up the transient parts will be on top. The only case I can think of that would really *need* this is if you have two menus that each overlaps the other when opened - one above that opens downward and one below that opens upward for example. If you have a lot of menus that might become necessary at times.

Comment (alexcjohnson) [reply src/components/updatemenus/draw.js]: Updatemenus were already smart enough to put the dropdown buttons (but not always-visible buttons) on top - exactly what I was suggesting 🎉 🏆 But there was a bug with this that if a new menu was added when other menus already existed, this would get added on top of the dropdown buttons -> fixed in https://github.com/plotly/plotly.js/pull/2121/commits/e0a10af575aa864365248a1e210961fb02bf8092

File: src/components/updatemenus/draw.js [hunk 3]
```diff
@@ -97,6 +97,9 @@ module.exports = function draw(gd) {
 
     // remove exiting header, remove dropped buttons and reset margins
     if(headerGroups.enter().size()) {
+        // make sure gButton is on top of all headers
+        gButton.node().parentNode.appendChild(gButton.node());
```
Comment (etpinard) [inline src/components/updatemenus/draw.js]: Nicely done.
