### PR TITLE
fix pie-like legend when line color array has length greater than 3

### LINKED ISSUE #3871: Pie legend color is not correct after the third one
[codepen](https://codepen.io/MojtabaSamimi/pen/qGmmWB?editors=0010)

### PR DESCRIPTION
**Pull request by archmoj**
Fix #3871.

@plotly/plotly_js

### CODE REVIEW

File: src/lib/index.js [hunk 1]
```diff
@@ -644,11 +643,7 @@ lib.minExtend = function(obj1, obj2) {
         if(k.charAt(0) === '_' || typeof v === 'function') continue;
         else if(k === 'module') objOut[k] = v;
         else if(Array.isArray(v)) {
-            if(k === 'colorscale') {
```
Comment (etpinard) [inline src/lib/index.js]: Hmm. This probably slows down performance in some cases. 

Can we make try adding another special (similar to `k === 'colorscale'`) instead?

Comment (alexcjohnson) [reply src/lib/index.js]: Or perhaps a third arg to the function, to override `arrayLen = 3`, that gets invoked only when needed?

Comment (etpinard) [reply src/lib/index.js]: > Or perhaps a third arg to the function, to override `arrayLen = 3`, that gets invoked only when needed?

Good call - that would work!

Comment (archmoj) [reply src/lib/index.js]: Revised in c960d0d6c3e1005f143c30e05aa795cb477010a6.

Comment (etpinard) [reply src/lib/index.js]: As `Lib.minExtend` is used in the toolpanel code, I would prefer if we would try to fix this bug without patching `Lib.minExtend`.

Sorry for the confusion @archmoj

Comment (alexcjohnson) [reply src/lib/index.js]: a third arg would be fine with toolpanel. I wouldn't want to add an exception like `color` because in some contexts that can be enormous. I would much prefer to pick out `pie` traces explicitly and extend the full length in that case, since we wouldn't be bothered by poor perf if someone gives us a pie with 100K slices 😏

**Comment by etpinard** [comment]
nicely done :dancer:
