### PR TITLE
 Fix scatter and scattergl hover on axes with period and adjust the unified hover position in respect to mean

### LINKED ISSUE #5822: hover misplaced with period positioning
In this pen the hover labels positioning is quite broken: https://codepen.io/nicolaskruchten/pen/gOWgpEx?editors=0010

when I hover directly on some of the points it's correct, but in general it's too far to the left. This doesn't happen when I use just the first trace, and when I set `xperiod` to e.g. M1.

### PR DESCRIPTION
**Pull request by archmoj**
Closes #5822.

@plotly/plotly_js

### CODE REVIEW

File: src/traces/scatter/calc.js [hunk 1]
```diff
@@ -51,23 +51,13 @@ function calc(gd, trace) {
         calcAxisExpansion(gd, trace, xa, ya, x, y, ppad);
     }
 
-    var hasPeriodX = !!trace.xperiodalignment;
```
Comment (nicolaskruchten) [inline src/traces/scatter/calc.js:54]: interesting that this PR is mostly removals :)

**Comment by nicolaskruchten** [comment]
Playing with this a bit, I'm noticing that the y-position of the unified label feels a bit weird... I thought it was set to be at the median of all the points it contained, or something like that, no?

**Comment by nicolaskruchten** [comment]
Also, if I run my cursor carefully up and down the left-most spikeline, I see the hoverlabel jump around in the y-dimension:

unified

File: src/traces/scatter/calc.js (hunk 1 above)
Comment (archmoj) [reply src/traces/scatter/calc.js:54]: Less is more :)

**Comment by archmoj** [comment]
> Playing with this a bit, I'm noticing that the y-position of the unified label feels a bit weird... I thought it was set to be at the median of all the points it contained, or something like that, no?

No. That's based on the winning point at the moment.
https://github.com/plotly/plotly.js/blob/990e260ee9437bc491e7f5e3defb183a37a17981/src/components/fx/hover.js#L1073-L1076
However we could possibly use median of y values on `x unified` and median of x on `y unified`.
If that's what you want please open a new issue for that.

**Comment by nicolaskruchten** [comment]
> That's based on the winning point at the moment

Is this something we changed in the v2 set of changes? I feel like I recall that when we first did this `x unified` feature it was based on the midpoint or something.

**Comment by archmoj** [comment]
> > That's based on the winning point at the moment
> 
> Is this something we changed in the v2 set of changes? I feel like I recall that when we first did this `x unified` feature it was based on the midpoint or something.

Positive: 
https://github.com/plotly/plotly.js/pull/5683/files
Screenshot from 2021-07-19 16-06-31

**Comment by archmoj** [comment]
Now addressed in https://github.com/plotly/plotly.js/pull/5836/commits/b44e11de463212ab79d5e22f258d125e1d298014

**Comment by nicolaskruchten** [comment]
Ah, much nicer! For some reason the hover for the left-most seems higher with respect to the data than the others... is that normal?

**Comment by archmoj** [comment]
> Ah, much nicer! For some reason the hover for the left-most seems higher with respect to the data than the others... is that normal?

Look normal to me: [demo](https://codepen.io/MojtabaSamimi/pen/vYmZwQP?editors=0010)

**Comment by nicolaskruchten** [comment]
Check out the position of the hover wrt the yellow and blue lines for the *right*-most (sorry, I mistakenly said left-most above)
unified

**Comment by archmoj** [comment]
> Check out the position of the hover wrt the yellow and blue lines for the _right_-most (sorry, I mistakenly said left-most above)
> unified

That works fine on my ubuntu using Chrome.

**Comment by nicolaskruchten** [comment]
Ok, we can fix that particular oddity later I guess :)

**Comment by nicolaskruchten** [comment]
Huh, this only happens in Observable, not in CodePen. Annoying! https://codepen.io/nicolaskruchten/pen/JjNJgxE

But ✨ from me!

File: test/jasmine/tests/gl2d_click_test.js [hunk 2]
```diff
@@ -627,6 +627,9 @@ describe('hover with (x|y)period positioning', function() {
 
     it('@gl shows hover info for scattergl', function(done) {
         Plotly.newPlot(gd, require('@mocks/gl2d_period_positioning.json'))
+        .then(function() { return Plotly.restyle(gd, 'xperiodalignment', 'start'); })
+        .then(function() { return Plotly.restyle(gd, 'yperiodalignment', 'start'); })
```
Comment (alexcjohnson) [inline test/jasmine/tests/gl2d_click_test.js:631]: Nonblocking, but these tests can be simplified (and sped up) with the object form
```
Plotly.restyle(gd,{xperiodalignment: 'start', yperiodalignment: 'start'})
```

File: test/jasmine/tests/hover_label_test.js [hunk 3]
```diff
@@ -2663,14 +2663,14 @@ describe('hover on traces with (x|y)period positioning', function() {
         .then(function() {
             assertHoverLabelContent({
                 name: 'scatter',
-                nums: '(Jan 2001, 1)'
+                nums: '(Jul 2001, 1)'
```
Comment (alexcjohnson) [inline test/jasmine/tests/hover_label_test.js:2666]: So these tests were actually locking down the incorrect behavior previously... This is why in general I think such tests should be self-contained rather than relying on a separate mock: you can read the test carefully and if the dimensions are nice and simple (ie you set round numbers for the size, margins, & axis ranges) you can manually verify that it's the desired behavior.

**Review by alexcjohnson — APPROVED** [review]
Excellent! Only non-blocking comments. 💃

File: test/jasmine/tests/gl2d_click_test.js (hunk 2 above)
Comment (archmoj) [reply test/jasmine/tests/gl2d_click_test.js]: Done in https://github.com/plotly/plotly.js/pull/5836/commits/17215ebd0d5d6cf13d0da1a5a5ce07b490741c7a
