### PR TITLE
Bring back geo trace toggle [fixes #244]

### LINKED ISSUE #244: Legend item toggling does not work for geo traces in v1.5.1
See: http://codepen.io/etpinard/pen/EPOrgN

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz 

Visibility toggling for geo traces has been broken since e8ebcb2e302850b68fb6a2653be4c870e399887a

This PR fixes it and adds tests.

### CODE REVIEW

File: src/plots/geo/geo.js [hunk 1]
```diff
@@ -153,8 +165,10 @@ proto.onceTopojsonIsLoaded = function(geoData, geoLayout) {
 
     var traceKeys = Object.keys(traceData);
     for(var j = 0; j < traceKeys.length; j++){
-        var traceKey = traceKeys[j];
-        Plots.getModule(traceKey).plot(this, traceData[traceKey], geoLayout);
+        var moduleData = traceData[traceKeys[j]];
+        var _module = moduleData[0]._module;
```
Comment (etpinard) [inline src/plots/geo/geo.js]: @mdtusz sorry for sneaking this in here.

I believe grabbing `_module` from the trace objects is more robust then relying on `Plots`. That way, a plot's required trace modules are scoped inside each plot state, instead of being library-wide globals.

**Comment by mdtusz** [comment]
Definitely a better way to go about it.

:dancer:
