### PR TITLE
Apply and ensure stroke event only to activate editable shapes

### LINKED ISSUE #4806: Shapes on below layer hides hover labels on 1.54.0
**Details**
I have a scatter plot with a shape background with `"layer": "below"` on version `1.53.0`. When upgrading the plot to version `1.54.0`, hover labels stops working. 

**How to reproduce**

Example: https://jsfiddle.net/jorgebg/2g0mb6tz/6/

1. Hover the data point of the center of the plot. The label doesn'tshow up. Hover labels of the data points on the sides work though.
2. Change the plotly.js version to `1.53.0` (line 5).
3. Hover the data point in the center of the plot and check the label shows up.

Code used in the example:

```
    const data = [{
        "x": ["2020-04-18T10:00:00.000Z", "2020-04-18T11:00:00.000Z", "2020-04-18T12:00:00.000Z", ],
        "y": [2.68, 2.42, 2.45],
        "type": "scatter",
      }];

      const shapes = [{
        "fillcolor": "#79bc6a",
        "layer": "below",
        "line": {
          "width": 0
        },
        "opacity": 0.2,
        "type": "rect",
        "x0": "2020-04-18T10:00:00.000Z",
        "x1": "2020-04-18T12:00:00.000Z",
        "xref": "x",
        "y0": 0,
        "y1": 15,
        "yref": "y"
      }];

      Plotly.newPlot("plot", data, {
        shapes: shapes,
      });
```

I checked the [release notes](https://github.com/plotly/plotly.js/releases) and I couldn't find any changes on the shapes API, I think this is a bug. Please let me know if you need more details. Thank you!

### LINKED ISSUE #4808: Can no longer pan/zoom when mousedown is on shapes
In 1.53.0 I was able to start a pan or zoom drag interaction on a shape: https://codepen.io/nicolaskruchten/pen/pojdmMv

In 1.54.0 I can't any more: https://codepen.io/nicolaskruchten/pen/XWmzLrN

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #4806 and fixes #4808 <del>also now one could strat drawing  over shapes no matter what the opacity of the below shape is</del>.

Codepen after: https://codepen.io/MojtabaSamimi/pen/WNQdQZv

@plotly/plotly_js 
@emmanuelle

### CODE REVIEW

File: src/components/shapes/draw.js [hunk 1]
```diff
@@ -163,15 +168,11 @@ function drawOne(gd, index) {
         } else {
             if(gd._context.edits.shapePosition) {
                 setupDragElement(gd, path, options, index, shapeLayer, editHelpers);
+            } else {
+                if(options.editable === true) {
+                    path.style('pointer-events', 'stroke');
```
Comment (alexcjohnson) [inline src/components/shapes/draw.js:173]: As long as this is scoped to `options.editable === true`, can't we still allow clicking on the fill when it's mostly opaque? `>0.5` seems a fine cutoff to me. I feel like that's the behavior people will expect - most importantly when there's no stroke but even when there is as long as there's a strong fill.

Comment (archmoj) [reply src/components/shapes/draw.js]: Revised in https://github.com/plotly/plotly.js/pull/4810/commits/078c007652bb4458c3d7a5ce1a61302403fc4dca.

File: test/jasmine/tests/draw_newshape_test.js [hunk 2]
```diff
@@ -1426,3 +1426,235 @@ describe('Activate and edit editable shapes', function() {
...
+                        y1: 2.5,
+                        fillcolor: 'blue',
+                        line: {
+                            width: 0,
+                            dash: 'dash',
+                            color: 'black'
+                        }
+                    }
+                ]
+            }, onfig: {
```
Comment (alexcjohnson) [inline test/jasmine/tests/draw_newshape_test.js:1644]:
```suggestion
            }, config: {
```

Comment (archmoj) [reply test/jasmine/tests/draw_newshape_test.js:1644]: typo of the week

**Comment by nicolaskruchten** [comment]
@archmoj re:
> now one could strat drawing over shapes no matter what the opacity of the below shape is.

do we need to change one  of the schema attribute descriptions to match this? I can't remember.

**Comment by archmoj** [comment]
> @archmoj re:
> 
> > now one could strat drawing over shapes no matter what the opacity of the below shape is.
> 
> do we need to change one of the schema attribute descriptions to match this? I can't remember.

@nicolaskruchten 
No. It was before applying https://github.com/plotly/plotly.js/pull/4810/commits/078c007652bb4458c3d7a5ce1a61302403fc4dca
in respect to @alexcjohnson's https://github.com/plotly/plotly.js/pull/4810#discussion_r419671172.
The PR description is modified above.
