### PR TITLE
fix for spikedistance=-1

### LINKED ISSUE #4626: spike lines do not appear when `spikedistance`
At least in some traces: https://codepen.io/antoinerg/pen/BaNYJve

To be clear, this test will fail: https://github.com/plotly/plotly.js/commit/9d1325c75c1526caf174f0c4c93504c8c71c8e81

Affects traces:
- bar
- ohlc

### PR DESCRIPTION
**Pull request by antoinerg**
Supersedes https://github.com/plotly/plotly.js/pull/4627 and fixes #4626 and #3805

For #4626:
Before: https://codepen.io/antoinerg/pen/BaNYJve
After: https://codepen.io/antoinerg/pen/oNXEENy

For #3805:
Before: https://codepen.io/antoinerg/pen/eYNMrBq
After: https://codepen.io/antoinerg/pen/ExjQQYw

cc @archmoj @alexcjohnson @etpinard

I opened issue https://github.com/plotly/plotly.js/issues/4638 to deal with an edge case.

### CODE REVIEW

**Comment by archmoj** [comment]
@antoinerg thanks for the follow ups!
Would you mind updating `before` codepen to use `v1.52.3` instead of latest?
That way one could easily compare the two after a new release.

File: src/traces/bar/hover.js [hunk 1]
```diff
@@ -161,7 +160,7 @@ function hoverOnBars(pointData, xval, yval, hovermode) {
     pointData.valueLabel = hoverLabelText(sa, pointData[sizeLetter + 'LabelVal']);
 
     // spikelines always want "closest" distance regardless of hovermode
-    pointData.spikeDistance = (sizeFn(di) + thisBarPositionFn(di)) / 2 + maxSpikeDistance - maxHoverDistance;
+    pointData.spikeDistance = (sizeFn(di) + thisBarPositionFn(di)) / 2 - maxHoverDistance;
```
Comment (antoinerg) [inline src/traces/bar/hover.js]: `maxHoverDistance` is necessary here because it is added in the function `sizeFn`. Now, why would a function compute the size of a bar would contain `maxHoverDistance` is beyond my comprehension.

File: test/jasmine/tests/hover_spikeline_test.js [hunk 2]
```diff
@@ -404,6 +404,29 @@ describe('spikeline hover', function() {
...
     });
 
+    it('correctly select the closest bar even when setting spikedistance to -1', function(done) {
+        var mock = require('@mocks/bar_stack-with-gaps');
+        var mockCopy = Lib.extendDeep({}, mock);
+        mockCopy.layout.xaxis.showspikes = true;
+        mockCopy.layout.yaxis.showspikes = true;
+        mockCopy.layout.spikedistance = -1;
+
+        Plotly.newPlot(gd, mockCopy)
```
Comment (archmoj) [inline test/jasmine/tests/hover_spikeline_test.js]: Non-blocking:
We could us `newPlot` > `plot` here.

File: test/jasmine/tests/hover_spikeline_test.js [hunk 3]
```diff
@@ -593,4 +616,139 @@ describe('spikeline hover', function() {
         .catch(failTest)
         .then(done);
     });
+
+    it('correctly draws lines up to the last point', function(done) {
+        Plotly.newPlot(gd, [
```
Comment (archmoj) [inline test/jasmine/tests/hover_spikeline_test.js]: Non-blocking:
We could us `newPlot` > `plot` here.

File: test/jasmine/tests/hover_spikeline_test.js [hunk 4]
```diff
@@ -593,4 +616,139 @@ describe('spikeline hover', function() {
...
+                        spikedistance: -1,
+                        xaxis: {showspikes: true},
+                        yaxis: {showspikes: true},
+                        zaxis: {showspikes: true},
+                        title: {text: trace.type},
+                        width: 400, height: 400
+                    }
+                };
+
+                Plotly.newPlot(gd, mock)
```
Comment (archmoj) [inline test/jasmine/tests/hover_spikeline_test.js]: Non-blocking:
We could us `newPlot` > `plot` here.

File: test/jasmine/tests/hover_spikeline_test.js (hunk 2 above)
Comment (alexcjohnson) [reply test/jasmine/tests/hover_spikeline_test.js]: Is that desirable? `plot` is not part of the API we want anyone using, so I'd kind of rather not use it in tests either, even if it's a little faster.

File: src/traces/bar/hover.js (hunk 1 above)
Comment (alexcjohnson) [reply src/traces/bar/hover.js]: Yeah, super confusing. It's not computing the size of a bar, it's computing a distance measure along the size axis. Is it necessary to remove `maxSpikeDistance` here? Or it just doesn't have an understood purpose?

File: test/jasmine/tests/hover_spikeline_test.js (hunk 2 above)
Comment (archmoj) [reply test/jasmine/tests/hover_spikeline_test.js]: Thanks for the note. Resolving...
And please feel free to open an issue if you prefer to chage similar cases in all the tests.

File: src/traces/bar/hover.js (hunk 1 above)
Comment (antoinerg) [reply src/traces/bar/hover.js]: > Is it necessary to remove maxSpikeDistance here?

Keeping `maxSpikeDistance` in leads to:
Screenshot_2020-03-13_15-47-32

> Or it just doesn't have an understood purpose?

I'll be honest: I also don't understand its purpose. What is `spikedistance` supposed to represent? Why would we add `maxSpikeDistance` and substract `maxHoverDistance` to it at the trace-level? It seems to me that this logic should live in `fx/hover.js` no?

File: test/jasmine/tests/hover_spikeline_test.js (hunk 2 above)
Comment (alexcjohnson) [reply test/jasmine/tests/hover_spikeline_test.js]: I wouldn't bother converting the rest unless there are problems. Sometimes there's a good reason to go for the faster one, in particular I seem to recall a lot of overhead to `newPlot` in WebGL tests? But that overhead comes with more assurance that there's no cross-test interaction, which has lead to hard-to-debug errors in the past. @etpinard any words of wisdom to add here?

File: src/traces/bar/hover.js (hunk 1 above)
Comment (alexcjohnson) [reply src/traces/bar/hover.js]: yeah this logic should certainly be cleaned up at some point... super hacky. Perhaps as part of #4638 🙏
