### PR TITLE
Adjust minfinalheight in automargin routine to allow narrow subplots e.g. gauge

### LINKED ISSUE #5314: Plot sizing issue in 1.58.0 release
The 1.58.0 release yesterday has changed (broken) some sizing behaviour we have in bullet charts. It appears that heights are not correct.

In releases prior to 1.58.0 we had a plot which looked like this:
image

When updating to 1.58.0 the same plot code now looks like this:
image

We are specifying widths and heights in the layout but it seems like they are not being adhered to in 1.58.0.

I have created a codepen which demonstrates the issue. In the codepen, if you change the plotly import version from 1.58.0 to a prior version, e.g. 1.57.0 then you will see the expected behaviour.
https://codepen.io/dmbarry86/pen/qBabyNa

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5314.

@plotly/plotly_js

### CODE REVIEW

File: src/plots/plots.js [hunk 1]
```diff
@@ -1866,8 +1866,8 @@ function initMargins(fullLayout) {
     if(!fullLayout._pushmarginIds) fullLayout._pushmarginIds = {};
 }
 
-var minFinalWidth = 64; // could possibly be exposed as layout.margin.minfinalwidth
-var minFinalHeight = 64; // could possibly be exposed as layout.margin.minfinalheight
```
Comment (alexcjohnson) [inline src/plots/plots.js:1870]: I think we should define two values for each dimension here (so repeat this for width as well):
```js
// non-negotiable - this is the smallest height we will allow users to specify via explicit margins
var MIN_SPECIFIED_HEIGHT = 2;

// could be exposed as an option - the smallest we will allow automargin to shrink a larger plot
var MIN_REDUCED_HEIGHT = 64;
```
Then down below we can combine these two:
```js
var minFinalHeight = Lib.constrain(
    height - margin.t - margin.b,
    MIN_SPECIFIED_HEIGHT,
    MIN_REDUCED_HEIGHT
);
```
The goal is:
- if you specify a plot height larger than `MIN_REDUCED_HEIGHT`, automargin is allowed to _increase_ the top and bottom margins to reduce the plot height as low as `MIN_REDUCED_HEIGHT`.
- if you specify a plot area smaller than `MIN_REDUCED_HEIGHT` but larger than `MIN_SPECIFIED_HEIGHT`, automargin will make no changes.
- if you specify a plot height smaller than `MIN_SPECIFIED_HEIGHT`, automargin should _reduce_ the margins symmetrically to increase the plot height back to `MIN_SPECIFIED_HEIGHT`

**Review by alexcjohnson — APPROVED** [review]
Beautiful. 💃
