### PR TITLE
Fix rounding big numbers in pie & sunburst traces

### LINKED ISSUE #5122: Pie show incorrect value (in scientific format) when hovered over
I am working with some large numbers in pie charts.  I came across some incorrect values in scientific format.  The value of L1 should be 3.31E+10 but it's showing 3.31E+1.  Same error is seen in L2.

image

Below is a snip of the code and here is a working example: [http://jsfiddle.net/3u05bo89/12/](http://jsfiddle.net/3u05bo89/12/).  
```
var data = [{
  values: [33103474584, 58115093734, 123036969165],
  labels: ['L1', 'L2', 'L3'],
  type: 'pie',
  hoverinfo: 'label+value+percent'
}];

var data = [{
  values: [33103474584, 58115093734, 123036969165],
  labels: ['L1', 'L2', 'L3'],
  type: 'pie',
  hoverinfo: 'label+value+percent'
}];

var layout = {
  height: 400,
  width: 400,
	title:"Test Piechart"
};

Plotly.newPlot('myDiv1', data, layout);
```

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5122 

@plotly/plotly_js

### CODE REVIEW

File: src/traces/pie/helpers.js [hunk 1]
```diff
@@ -20,7 +20,9 @@ exports.formatPiePercent = function formatPiePercent(v, separators) {
 
 exports.formatPieValue = function formatPieValue(v, separators) {
     var vRounded = v.toPrecision(10);
-    if(vRounded.lastIndexOf('.') !== -1) {
+    if(vRounded.indexOf('e+') !== -1) {
+        vRounded = Math.round(v);
+    } else if(vRounded.lastIndexOf('.') !== -1) {
```
Comment (alexcjohnson) [inline src/traces/pie/helpers.js:25]: There's also `e-` if the number is <1e-6

Can we do something like:
```
if(vRounded.indexOf('e') !== -1) {
    vRounded = vRounded.replace(/[.]?0+e/, 'e');
} else if(vRounded.indexOf('.') !== -1) { // why did we have lastIndexOf here? indexOf should be the same, right?
```

File: test/jasmine/tests/pie_test.js [hunk 2]
```diff
@@ -2064,3 +2064,72 @@ describe('pie uniformtext', function() {
...
+                1234.56789012,
+                123.456789012,
+                12.3456789012,
+                1.23456789012,
+                0.123456789012,
+                0.0123456789012,
+                0.00123456789012,
+                0.000123456789012,
+                0.0000123456789012,
+                0.00000123456789012,
```
Comment (alexcjohnson) [inline test/jasmine/tests/pie_test.js:2101]: heh you just needed to add one more zero to get `e-` 😅 But I think it makes sense to keep `e+/-` in the result when that's what `toPrecision` does - eventually when the number gets big enough (or small enough) that'll be necessary instead of `round`.

File: src/traces/pie/helpers.js (hunk 1 above)
Comment (archmoj) [reply src/traces/pie/helpers.js]: Good call. Revised in https://github.com/plotly/plotly.js/pull/5152/commits/58916511f71c2f6c58364735f5acc95b49687246.

File: test/jasmine/tests/pie_test.js (hunk 2 above)
Comment (archmoj) [reply test/jasmine/tests/pie_test.js:2101]: Good call. Revised in 5891651.

**Review by alexcjohnson — APPROVED** [review]
Excellent! 💃
