### PR TITLE
Fix `line.width` attr declaration in *contour traces

### LINKED ISSUE #4203: [Bug] data[type=contour].line width documentation typo
As per my tests , it seems that 
for ```data[type=contour].line.width```
default value is ```0.5``` instead of documented ```2```

 https://plot.ly/javascript/reference/#contour-line-width

### PR DESCRIPTION
**Pull request by etpinard**
fixes #4203 

- unset dflt in contour `line.width`, explain default logic in description
- reuse contour `line` declaration in contourcarpet
- set hard dflt in histogram2dcontour `line.width` declaration,
  as histogram2dcontour trace only support level-style contours
  at the moment.

cc @archmoj

### CODE REVIEW

File: src/traces/contour/attributes.js [hunk 1]
```diff
@@ -239,9 +239,17 @@ module.exports = extendFlat({
...
+        width: {
+            valType: 'number',
+            min: 0,
+            role: 'style',
+            editType: 'style+colorbars',
+            description: [
+                'Sets the contour line width in (in px)',
+                'Defaults to *0.5* when `contours.type` is *levels*.',
+                'Defaults to *2* when `contour.type` is *constraint*.'
+            ].join(' ')
```
Comment (etpinard) [inline src/traces/contour/attributes.js]: Here's the corresponding default logic:

https://github.com/plotly/plotly.js/blob/1dee68b7fdd768c5dbc4b3644d4bcbd15f8e591a/src/traces/contour/style_defaults.js#L25

reused by `contourcarpet` and `histogram2dcontour`

https://github.com/plotly/plotly.js/blob/1dee68b7fdd768c5dbc4b3644d4bcbd15f8e591a/src/traces/contour/constraint_defaults.js#L46

reused by `contourcarpet`

**Comment by archmoj** [comment]
@etpinard Nicely done.
:dancer:
