### PR TITLE
Fix logic for display modebar plot config [fixes #56]

### LINKED ISSUE #56: modebar can't be hidden with multiple traces
It looks like the mode bar can't be hidden in line charts with more than one trace (though it works fine for single trace charts).

Here's a minimal example:

```
<html>
<body>
  <div id="plotly-div"></div>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>

var trace1 = { x: [0, 1], y: [4, 5], type: "scatter"};
var trace2 = { x: [0, 1], y: [4, 5], type: "scatter"};
//var data = [trace1];  // This works: the mode bar gets removed.
var data = [trace1, trace2];  // This doesn't work: the mode bar remains.
Plotly.plot('plotly-div', data, {}, { displayModeBar: false });

</script>
</body>
</html>
```

I looked through the code a bit and thought that perhaps this has something to do with [this comment](https://github.com/plotly/plotly.js/blob/216599856f6757333c34c29fb2f3786f8f02cf9b/src/plot_api/plot_api.js#L2466).

### PR DESCRIPTION
**Pull request by etpinard**
@bpostlethwaite 

Fixes some incomplete logic.

### CODE REVIEW

File: src/components/modebar/manage.js [hunk 1]
```diff
@@ -27,9 +27,11 @@ module.exports = function manageModeBar(gd) {
...
         modeBar = fullLayout._modeBar;
 
-    if(!context.displayModeBar && modeBar) {
-        modeBar.destroy();
-        delete fullLayout._modeBar;
+    if(!context.displayModeBar) {
+        if(modeBar) {
+            modeBar.destroy();
+            delete fullLayout._modeBar;
+        }
```
Comment (etpinard) [inline src/components/modebar/manage.js]: before, `displayModeBar` was only handle when updating an existing mode bar.

**Comment by bpostlethwaite** [comment]
:dancer:
