### PR TITLE
Fix heatmap/image traces without zsmooth on Safari/iOS

### LINKED ISSUE #6604: 2.23.0: Setting zsmooth to false for heatmaps seems to be ignored or isn't working in zsmooth on some OS+Browsers e.g. Safari and iPad/iPhone Chrome
With version 2.23.0, it seems like the `data[type=heatmap]` zsmooth property to `false` does not seem to have any effect in Safari (tested in 16.4.1 on macOS Monterey and macOS Ventura, also Safari for iOS 16.4).

No matter what the value is set to, Safari renders the heatmap as a big blurry mess; while, it is nice and crisp rendered in Firefox and Chrome.

Codepen Example: https://codepen.io/theqlp/pen/Poyayop

The issue seems to be a regression from 2.22.0 and can be replicated by changing the script tag in the codepen from:

```html
<script src="https://cdn.plot.ly/plotly-2.23.0.min.js"></script>
```

to:

```html
<script src="https://cdn.plot.ly/plotly-2.22.0.min.js"></script>
```

I have posted screenshots showing the behavior of 2.20.0 and 2.23.0 in macOS Safari, 2.23.0 in Firefox and Chrome, and 2.23.0 in Safari for iOS: https://imgur.com/a/m75ozkP

### PR DESCRIPTION
**Pull request by lvlte**
Fixes #6604

Safari doesn't behave consistently with pixelated image-rendering (depends on whether the target object is an `<image>` or an ``, whether there is a transform applied on the object, etc.) although it's supposed to support it and even though it passes the css support test. It seems like a webkit bug (it should not pass the css support test) ? 

So I guess the best option for now is to prevent the pixelated rendering optimization on Safari.

### CODE REVIEW

File: src/lib/supports_pixelated_image.js [hunk 1]
```diff
@@ -15,7 +15,8 @@ function supportsPixelatedImage() {
     if(_supportsPixelated !== null) { // only run the feature detection once
         return _supportsPixelated;
     }
-    if(Lib.isIE()) {
+    if(Lib.isIE() || Lib.isSafari()) {
```
Comment (alexcjohnson) [inline src/lib/supports_pixelated_image.js:18]: Per the discussion in #6604 seems like this is a problem with all webkit browsers. Unfortunately Chrome [say it's webkit](https://security.stackexchange.com/questions/126407/why-does-chrome-send-four-browsers-in-the-user-agent-header) in its `userAgent` so perhaps the best we can do is also include iOS?

```suggestion
    if(Lib.isIE() || Lib.isSafari() || lib.isIOS()) {
```

Comment (lvlte) [reply src/lib/supports_pixelated_image.js:18]: Yes for now it sounds more reasonable to just exclude Safari/IOS. I was searching for a way to clearly identify the actual rendering engine in use, but feel like it won't be safe or it would require more time to investigate further.

File: src/lib/supports_pixelated_image.js [hunk 2]
```diff
@@ -15,7 +15,8 @@ function supportsPixelatedImage() {
     if(_supportsPixelated !== null) { // only run the feature detection once
         return _supportsPixelated;
     }
-    if(Lib.isIE()) {
+    if(Lib.isIE() || Lib.isSafari() || lib.isIOS()) {
```
Comment (archmoj) [inline src/lib/supports_pixelated_image.js:18]:
```suggestion
    if(Lib.isIE() || Lib.isSafari() || Lib.isIOS()) {
```

File: src/lib/supports_pixelated_image.js [hunk 3]
```diff
@@ -15,7 +15,8 @@ function supportsPixelatedImage() {
     if(_supportsPixelated !== null) { // only run the feature detection once
         return _supportsPixelated;
     }
-    if(Lib.isIE()) {
+    if(Lib.isIE() || Lib.isSafari() || Lib.isIOS()) {
+        // NB. Safari passes the test below but the final rendering is not pixelated
```
Comment (archmoj) [inline src/lib/supports_pixelated_image.js:19]: We should possibly disable this feature when `window.navigator.userAgent` is empty.
Also to make debugging easier we may rewrite this function something like: 
```js
function supportsPixelatedImage() {
    if(_supportsPixelated !== null) { // only run the feature detection once
        return _supportsPixelated;
    }

    _supportsPixelated = false;

    if(!(
        !window.navigator.userAgent ||
        Lib.isSafari() ||
        Lib.isIOS() ||
        Lib.isIE()
    )) {
        var declarations = Array.from(constants.CSS_DECLARATIONS).reverse();

        var supports = (window.CSS && window.CSS.supports) || window.supportsCSS;
        if(typeof supports === 'function') {
            _supportsPixelated = declarations.some(function(d) {
                return supports.apply(null, d);
            });
        } else {
            var image3 = Drawing.tester.append('image')
                .attr('style', constants.STYLE);

            var cStyles = window.getComputedStyle(image3.node());
            var imageRendering = cStyles.imageRendering;

            _supportsPixelated = declarations.some(function(d) {
                var value = d[1];
                return (
                    imageRendering === value ||
                    imageRendering === value.toLowerCase()
                );
            });

            image3.remove();
        }
    }

    return _supportsPixelated;
}
```

**Comment by archmoj** [comment]
For the `download` issue that you mentioned [here](https://github.com/plotly/plotly.js/issues/6604#issuecomment-1548470756), we could use similar logic as applied by `image` trace. 
See:
https://github.com/plotly/plotly.js/blob/18b509795372ae3ae8a0e81969a6400408511e30/src/traces/image/plot.js#L15
