### PR TITLE
Legend scroll fix

### LINKED ISSUE #2387: Clicking legend item causes legend to scroll
Taking from https://community.plot.ly/t/clicking-legend-entry-causes-legend-to-scroll/3361

This came up in the Dash workshop with one of the attendee's apps. When they click on a legend item, the legend scrolls before the click is fired, causing the legend click to fire on a different item. Very annoying!

One of the attendees and I recreated an example here: https://codepen.io/chubukov/pen/rJdZdz?editors=0010. I can't get it ti misbehave on my computer, but the attendee can. The attendee claims that it is part of the grouped legend functionality, as this example (without groups) https://codepen.io/chriddyp/pen/RQMBmJ?editors=1111 works fine for them.

Attendee says:
> I wonder if it has something to do with the extra entries per legendgroup. I played with markers vs lines also, don't think that matters.
> It's only clicking in specific spots that triggers the scroll. It seems to be just under the letters that tends to do it. Maybe just when the pointer is about to shift from the hand to the arrow? Not sure exactly, maybe there's some automated way to click in every pixel and see?

### PR DESCRIPTION
**Pull request by alexcjohnson**
Fixes #2387 - don't allow dragging from the scroll box of a legend, only from the scroll bar itself, and even then not on right clicks, only left click. I also made the scroll bar handle a little bit wider so it's a bit easier to grab. And another part of the issue is that the scrollbar would jump to be centered on the mouse cursor, rather than simply moving with it from wherever you grabbed it. I fixed that too.

Fixes the legend part of #1859 - makes the scrollbar scale to show the fraction of the legend that's visible.

cc @etpinard

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Since this doesn't show up in test images, here's what the new scrollbars look like - a little wider and a lot taller:
screen shot 2018-02-28 at 4 21 05 pm

File: test/jasmine/tests/legend_scroll_test.js [hunk 1]
```diff
@@ -96,6 +97,69 @@ describe('The legend', function() {
...
+            mouseEvent('mousedown', x, y0, opts);
+            mouseEvent('mousemove', x, y1, opts);
+            mouseEvent('mouseup', x, y1, opts);
+
+            expect(finalDataScroll).not.toBe(initialDataScroll);
+
+            return finalDataScroll;
+        }
+
+        it('should scroll on dragging the scrollbar', function() {
```
Comment (etpinard) [inline test/jasmine/tests/legend_scroll_test.js]: Are these general legend scrollbox tests and/or tests that :lock: the fix for #2387? (I'm asking as I would be surprised if #2387 was reproducible in a jasmine test).

**Comment by etpinard** [comment]
Probably related to https://github.com/plotly/plotly.js/issues/808. The new variable-height scroll bar doesn't update. For example, from [`legend_scroll`](https://rreusser.github.io/plotly-mock-viewer/#legend_scroll) repeatedly calling `Plotly.deleteTraces(gd, [0])` gives:

peek 2018-02-28 16-47

No need to fix this in this PR though, just confirming that scrollable legends don't update well as first reported in https://github.com/plotly/plotly.js/issues/808

File: test/jasmine/tests/legend_scroll_test.js (hunk 1 above)
Comment (alexcjohnson) [reply test/jasmine/tests/legend_scroll_test.js]: Yes, these do test #2387, if I'm interpreting it correctly. What I think was happening in #2387 is that *somehow* the [`scrollBox` drag](https://github.com/plotly/plotly.js/pull/2426/commits/f75f5ba325e7c80d93272b71585d0e31ceac4f48#diff-f48c57dae9095e916f13f364ae740f69L296) was being triggered - and that's what I decided (with no dissent) had no reason ever to happen. So this test shows that regular drag works, then the [next one](https://github.com/plotly/plotly.js/pull/2426/commits/f75f5ba325e7c80d93272b71585d0e31ceac4f48#diff-ed9e861dab1a2e0cbdeacb9c7bd74db1R145) shows that the `scrollBox` won't drag even if it does somehow get the event, and then the [third new test](https://github.com/plotly/plotly.js/pull/2426/commits/f75f5ba325e7c80d93272b71585d0e31ceac4f48#diff-ed9e861dab1a2e0cbdeacb9c7bd74db1R154) shows that right-click (the only form of #2387 I could reproduce on my own computer) even on the `scrollBar` will not trigger drag.

File: test/jasmine/tests/legend_scroll_test.js [hunk 2]
```diff
@@ -100,19 +101,19 @@ describe('The legend', function() {
...
                 2 * constants.scrollBarMargin;
             var initialDataScroll = scrollBox.getAttribute('data-scroll');
             var dy = 50;
             var finalDataScroll = '' + Lib.constrain(initialDataScroll -
                 dy / scrollBarYMax * scrollBoxYMax,
                 -scrollBoxYMax, 0);
 
-            var scrollBarBB = scrollBar.getBoundingClientRect();
-            var y0 = scrollBarBB.top + scrollBarBB.height / 2;
+            var y0 = scrollBarBB.top + scrollBarBB.height / 5;
```
Comment (alexcjohnson) [inline test/jasmine/tests/legend_scroll_test.js]: notice that I moved the drag point away from the center of the `scrollBar`, thereby testing that it drags from where you grab it rather than snapping to the center.

**Comment by alexcjohnson** [comment]
Fixed #808 (and https://github.com/plotly/plotly.js/pull/2426#issuecomment-369395487) in https://github.com/plotly/plotly.js/pull/2426/commits/569b37893c7082e9ed43740dd87a2d2fc36ce41b

File: src/components/legend/draw.js [hunk 3]
```diff
@@ -234,9 +241,10 @@ module.exports = function draw(gd) {
             scrollBarHeight -
             2 * constants.scrollBarMargin;
         var scrollBoxYMax = opts._height - legendHeight;
+        var scrollRatio = scrollBarYMax / scrollBoxYMax;
 
-        var scrollBarY = constants.scrollBarMargin;
-        var scrollBoxY = scrollBox.attr('data-scroll') || 0;
```
Comment (etpinard) [inline src/components/legend/draw.js]: Yes. Way better to use `_` then a DOM attr :tada:

File: src/components/legend/draw.js [hunk 4]
```diff
@@ -243,8 +243,7 @@ module.exports = function draw(gd) {
         var scrollBoxYMax = opts._height - legendHeight;
         var scrollRatio = scrollBarYMax / scrollBoxYMax;
 
-        // scrollBoxY is 0 or a negative number
-        var scrollBoxY = Math.max(opts._scrollY || 0, -scrollBoxYMax);
+        var scrollBoxY = Math.min(opts._scrollY || 0, scrollBoxYMax);
```
Comment (etpinard) [inline src/components/legend/draw.js]: Thank you!

**Comment by etpinard** [comment]
Amazing PR! :dancer:
