### PR TITLE
fix line decimation for segments crossing the viewport

### LINKED ISSUE #2664: Line that should render on x axis rendered above it
When plotting a line chart with several points at (x,0) the interpolated line between them renders above the X axis line for certain data sets.

You can view an example [here](https://jsfiddle.net/bh0etd08/). Zoom in such that your x window is roughly 2 to 1 and your y window is -0.04 to .06. As you continue to zoom you will see the incorrect line, even though the only points in that portion of the chart are: (-1,0) and (3.214112,0).

newplot

Thanks,
Jon

### PR DESCRIPTION
**Pull request by alexcjohnson**
Fixes #2664 - the problem was the increasing decimation tolerance as points get farther from the viewport - if a *segment* crosses the viewport we need to use the on-screen (minimum) tolerance even though points on both sides are far enough away to get a high tolerance. Adds a little extra calculation into the decimation algorithm unfortunately, but I don't think it's too big a hit (nor do I see any higher-performance alternative).

cc @etpinard

### CODE REVIEW

File: test/jasmine/tests/scatter_test.js [hunk 1]
```diff
@@ -472,6 +474,47 @@ describe('Test scatter', function() {
                 expect(ptsOut2[0]).toBeCloseTo2DArray(ptsExpected[i].map(reverseXY), 1, i);
             });
         });
+
+        it('works when far off-screen points cross the viewport', function() {
```
Comment (etpinard) [inline test/jasmine/tests/scatter_test.js]: Nicely done. :dancer:
