### PR TITLE
React mapbox style

### LINKED ISSUE #4719: Fail to react to tiles in mapbox.style.sources
Originally reported in https://github.com/plotly/dash/issues/1152.
[MINIMAL DEMO](https://codepen.io/MojtabaSamimi/pen/dyoLood?editors=0010)

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #4719.

@plotly/plotly_js

### CODE REVIEW

File: src/plots/mapbox/mapbox.js [hunk 1]
```diff
@@ -151,7 +151,7 @@ proto.updateMap = function(calcData, fullLayout, resolve, reject) {
     var promises = [];
     var styleObj = getStyleObj(opts.style);
 
-    if(self.styleObj.id !== styleObj.id) {
```
Comment (alexcjohnson) [inline src/plots/mapbox/mapbox.js:154]: At first I was concerned about order of keys:
```js
JSON.stringify({a: 1, b: 2}) !== JSON.stringify({b: 2, a: 1})
```
But I see we're making `styleObj` in a predictable order in the `getStyleObj` function, so this should be robust 🎉

File: src/plots/mapbox/mapbox.js [hunk 2]
```diff
@@ -63,8 +63,8 @@ proto.plot = function(calcData, fullLayout, promises) {
         self.map.remove();
         self.map = null;
         self.styleObj = null;
-        self.traceHash = [];
-        self.layerList = {};
+        self.traceHash = {};
+        self.layerList = [];
```
Comment (alexcjohnson) [inline src/plots/mapbox/mapbox.js:67]: 😂
