### PR TITLE
Clarify color attribute descriptions

### LINKED ISSUE #331: more instructions on colorscale, cmin, cmax, and color
Background: I was trying to use a custom color mapping on a 3D scatter plot, and specifically, I want an upper bound and lower bound on my colorscale. While I knew I should use cmin and cmax, I failed to understand the connections between them, color and colorscale.

The current document says: 

> cmin (number) 
Has only an effect if `marker.color` is set to a numerical array. Sets the lower bound of the color domain.

> colorscale (colorscale) 
Sets the colorscale. The colorscale must be an array containing arrays mapping a normalized value to an rgb, rgba, hex, hsl, hsv, or named color string. At minimum, a mapping for the lowest (0) and highest (1) values are required. For example, `[[0, 'rgb(0,0,255)', [1, 'rgb(255,0,0)']]`. _(1)_To control the bounds of the colorscale in color space, use cmin and cmax

> color (color) 
Sets the marker color.

The problem lays on the documentation for color. It only specifies one situation, which is that we want a single color for all points. However, it does not show how to set the array for the color in order to get colorscale to work. In addition to that, cmin and cmax should specify that it should use a value associated with the color array, not the colorscale. It is very misleading to put _(1)_ in that spot. 

PS. _(1)_ is the last sentence of colorscale spec. For some reason, italic does not work inside a quote.

### PR DESCRIPTION
**Pull request by mdtusz**
Resolves #331 

It's tricky to be *crystal* clear in these, but I think this gets the point across.

@cldougl @etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
Much better. :+1: for me

I'll let @cldougl give it another look though.

File: src/traces/scatter/attributes.js [hunk 1]
```diff
@@ -332,8 +345,16 @@ module.exports = {
...
-                    'Sets the colorscale.'
+                    'Sets the colorscale and only has an effect',
+                    'if `marker.line.color` is set to a numerical array.',
+                    'The colorscale must be an array containing',
+                    'arrays mapping a normalized value to an',
+                    'rgb, rgba, hex, hsl, hsv, or named color string.',
+                    'At minimum, a mapping for the lowest (0) and highest (1)',
+                    'values are required. For example,',
+                    '`[[0, \'rgb(0,0,255)\', [1, \'rgb(255,0,0)\']]`.',
+                    'To control the bounds of the colorscale in color space,',
```
Comment (cldougl) [inline src/traces/scatter/attributes.js]: color space :star:  :rainbow: :star:

File: src/traces/scatter/attributes.js [hunk 2]
```diff
@@ -283,7 +290,8 @@ module.exports = {
             role: 'info',
             description: [
                 'Has only an effect if `marker.color` is set to a numerical array.',
-                'Sets the lower bound of the color domain.'
+                'Sets the lower bound of the color domain.',
```
Comment (cldougl) [inline src/traces/scatter/attributes.js]: Since we're making this *super* explicit (and using `cmin` AND `cmax` was mentioned in the issue: https://github.com/plotly/plotly.js/issues/331#issuecomment-196514964) - I would vote to add: must be used w/ `cmax` here as well.

File: src/traces/scatter/attributes.js [hunk 3]
```diff
@@ -274,7 +280,8 @@ module.exports = {
             role: 'info',
             description: [
                 'Has only an effect if `marker.color` is set to a numerical array.',
-                'Sets the upper bound of the color domain.'
+                'Sets the upper bound of the color domain.',
```
Comment (cldougl) [inline src/traces/scatter/attributes.js]: and vice versa: use w/ `cmin`

File: src/traces/scatter/attributes.js [hunk 4]
```diff
@@ -352,7 +373,8 @@ module.exports = {
                 role: 'info',
                 description: [
                     'Has only an effect if `marker.line.color` is set to a numerical array.',
-                    'Sets the upper bound of the color domain.'
+                    'Sets the upper bound of the color domain.',
```
Comment (cldougl) [inline src/traces/scatter/attributes.js]: + the w/ `cmin` explicitness

File: src/traces/scatter/attributes.js [hunk 5]
```diff
@@ -361,7 +383,8 @@ module.exports = {
                 role: 'info',
                 description: [
                     'Has only an effect if `marker.line.color` is set to a numerical array.',
-                    'Sets the lower bound of the color domain.'
+                    'Sets the lower bound of the color domain.',
```
Comment (cldougl) [inline src/traces/scatter/attributes.js]: + the w/ `cmax` explicitness

**Comment by cldougl** [comment]
:dancer: from me!
Looks much more clear!
