### PR TITLE
fix(violin): prevent FP drift in KDE sampling loop (avoid underrun/overrun on tiny spans)

### LINKED ISSUE #7581: [BUG]: Violin calc density loop fails with tiny/near-equal spans - underrun ('undefined.v') or overrun (timeout)
### Description

violin traces can fail or hang when y values contain high-precision floats that differ in precision.
This causes either:

- Underrun: the internal KDE density array is not fully populated - "Cannot read properties of undefined (reading 'v')"
- Overrun: the density loop runs one extra iteration - "TimeoutError".

### Screenshots/Video

Image

### Steps to reproduce

minimal reproduction:

```py
Plotly.newPlot("myDiv", {
   "data":[
      {
         x: [0,0], y: [0.5006312999999999, 0.5006313],
         type:"violin"
      }
   ]
})
```

This code pen shows the in correct calculations happening for both cases (over run and underrun):

https://codepen.io/Koookadooo/pen/gbPxEVy?editors=0012

I have also attached a file of a python script showing both the "TimeoutError" and the "Cannot read properties of undefined (reading 'v')" using a larger set of high precision variable floating point numbers.

[debug_html.py](https://github.com/user-attachments/files/22893384/debug_html.py)

To run: 

- Python debug_html.py
- input 'y' to open files in browser to observe errors

### Root Cause

src/traces/violin/calc.js currently generates KDE samples like this:

```js
for (var k = 0, t = span[0]; t < (span[1] + step / 2); k++, t += step) {
    var v = kde(t);
    cdi.density[k] = {v: v, t: t};
    maxKDE = Math.max(maxKDE, v);
}
```

When step is extremely small (≈1e-14), repeated floating-point addition in t += step accumulates error:

- In some spans, t exceeds span[1] + step/2 early → underrun (holes or shorter array).
- In others, drift keeps t below the limit too long → overrun (extra sample).

### Suggested fix

Instead, compute t fresh each iteration from the integer index k:

```diff
- for (var k = 0, t = span[0]; t < (span[1] + step / 2); k++, t += step) {
+ for (var k = 0; k < n; k++) {
+     var t = span[0] + k * step;
      var v = kde(t);
      cdi.density[k] = { v: v, t: t };
      maxKDE = Math.max(maxKDE, v);
}
```

### Notes

**Related:** supercedes [plotly/plotly.js#6490](https://github.com/plotly/plotly.js/issues/6490)

That issue was closed as stale, but a maintainer noted that a PR would be welcome.

This report includes a confirmed repro and working fix.

I will be making a Pull Request next with the working fix referencing this issue.

### PR DESCRIPTION
**Pull request by Koookadooo**
Fixes #7581 
Supersedes [plotly/plotly.js#6490](https://github.com/plotly/plotly.js/issues/6490)

### Summary
Replace cumulative `t += step` loop in `src/traces/violin/calc.js` with an index-based loop to eliminate floating-point drift when spans are extremely small (≈1e-13).

With near-equal, high-precision values, the KDE sampling loop accumulates FP error via `t += step`. Depending on drift direction this can:
- **Underrun:** stop early and leave the tail of `cdi.density` unfilled → `Cannot read properties of undefined (reading 'v')` (often seen via Kaleido).
- **Overrun:** iterate once too many → severe slowness / `TimeoutError` during export.

This PR computes `t` from the integer index on each iteration so `density.length === n` deterministically and avoids cumulative error.

### Change (logic only)

```diff
- for (var k = 0, t = span[0]; t < (span[1] + step / 2); k++, t += step) {
+ for (var k = 0; k < n; k++) {
+     var t = span[0] + k * step;
      var v = kde(t);
      cdi.density[k] = { v: v, t: t };
      maxKDE = Math.max(maxKDE, v);
}
```
Why it works:

We already compute ```n = Math.ceil(dist / (bandwidth/3))``` and ```step = dist / n```. Index-based sampling guarantees exactly ```n``` points with no cumulative drift, fixes both failure modes, and preserves existing spacing and scaling.

### Tests
Added a jasmine test in `test/jasmine/tests/violin_test.js`:

```js
it('should produce exactly n density samples for tiny or near-equal spans', function() {
    var cd = _calc({
        type: 'violin',
        x: [0, 0],
        y: [0.5006312999999999, 0.5006313]
    });
    var cdi = cd[0];

    var dist = cdi.span[1] - cdi.span[0];
    var n = Math.ceil(dist / (cdi.bandwidth / 3));

    expect(cdi.density.length).toBe(n);
});
```
verified locally with:
```
npm run lint
npm run test-jasmine -- violin
```

### Demo

* CodePen comparison (old vs fixed):

https://codepen.io/Koookadooo/pen/PwZKrrv?editors=1111

* Local file for download to run manually:

[calc_test.js](https://github.com/user-attachments/files/22893621/calc_test.js)

run with:
```
node calc_test.js
```

* Python script will now render plots when pointed at the fixed code and built code as opposed to the CDN example in #7581:

[debug_html.py](https://github.com/user-attachments/files/22893855/debug_html.py)

to run, build my branch locally with:
```
npm run build
```
or 
```
npm run bundle
```
and then run:
```
python debug_html.py --plotly-js "path\to\local\build\plotly.js" --open
```

### Impact

- Fixes ```Cannot read properties of undefined (reading 'v')``` and ```TimeoutError``` in KDE sampling.
- No schema or layout changes.
- Performance neutral or slightly improved.

### CODE REVIEW

**Comment by Koookadooo** [comment]
Not sure why diff images in tests are failing I checked these against plotly's test_dashboard using the following:

```
npm install
npm run pretest
npm run start
```

Original Code:

image

violin_non-linear image in test_dashboard:

image

Change in code to ensure test_dashboard is picking up my changes (n = 3):

image

```Tabs.reload()```

violin_non-linear image in test_dashboard:

image

My Proposed Fix:

image

```Tabs.reload()```

violin_non-linear image in test_dashboard:

image

***

Unless all of the diff images just show the difference in the pixels between the base and the new plot renders. In that case, all of the differences appear at the ends of the violin shapes, which makes sense — the old loop accumulated floating-point rounding error, so the violin tips were drawn slightly differently each time. With the new index-based sampling, the KDE grid is consistent and removes that drift, which explains these small end-cap differences.

**Comment by emilykl** [comment]
> Unless all of the diff images just show the difference in the pixels between the base and the new plot renders. In that case, all of the differences appear at the ends of the violin shapes, which makes sense — the old loop accumulated floating-point rounding error, so the violin tips were drawn slightly differently each time. With the new index-based sampling, the KDE grid is consistent and removes that drift, which explains these small end-cap differences.

@Koookadooo Yes, this is correct. The `test-baselines` CI job renders each test plot according to the updated code, and compares the resulting image to the "ground truth" images stored in `test/image/baselines/`.

So when making a change that affects how a plot is displayed visually, it's normal and appropriate that some of the image tests will fail, and what it it means is that the baseline images need to be updated.

Once you've convinced yourself that the changes are expected, you can download the updated images as artifacts from the CI job and commit them. If you rebase off of `master` you can use the `tasks/circleci_image_artifact_download.sh` script @camdecoster added to do that.

FWIW I've pushed a commit on a separate branch [here](https://github.com/plotly/plotly.js/commit/f4662c8446c31289a86ca003fb8f95d0f51625f1) with the new images so that I could use GitHub's diff interface to see the changes easily. It looks like in general the effect is that some of the ends of the violins are chopped shorter. Is that expected?

**Comment by Koookadooo** [comment]
@emilykl No, the chopped ends were not expected. The first change ended up sampling to span[1] - step (dist /n) which ended up leaving off the end point.

Upon further inspection, the cdi.density was being set to n where n is the number of intervals (Math.ceil(dist / (bandwidth/3))). With step = dist / n there are n intervals meaning we have n+1 interval points, so to deterministically include both span endpoints we must sample n+1 points. The original t-based loop (t += step with t < span[1] + step/2) implicitly allowed that endpoint sample but relied on incremental addition, which accumulated floating-point drift and made iteration counts non-deterministic. Changing to index-based sampling and allocating cdi.density = new Array(n + 1) lets us compute each t as span[0] + k*step (no accumulation), so we deterministically include the endpoint and avoid drift. 

This approach ended up only producing 1 test baseline image failure and it failed by 3 pixels. It also fixes the original floating point accumulation issue that caused the timeout or undefined errors.

**Comment by emilykl** [comment]
@Koookadooo Thanks for the thorough explanation, that makes sense.

It's not surprising to me that one of the violin baselines would change imperceptibly as a result of these changes, so that's fine as well.

Does that mean these changes are ready for another review? I'll take a final look through within the next day or two.

**Comment by Koookadooo** [comment]
@emilykl Yes, ready for review. Cheers!

Also, thanks for committing the new images and linking the diff, that made it easy to see what was happening.

File: src/traces/violin/calc.js [hunk 1]
```diff
@@ -48,9 +48,11 @@ module.exports = function calc(gd, trace) {
             }
 
             var kde = helpers.makeKDE(cdi, trace, vals);
-            cdi.density = new Array(n);
+            // n intervals means n + 1 sample points to include both endpoints
+            cdi.density = new Array(n + 1);
 
-            for(var k = 0, t = span[0]; t < (span[1] + step / 2); k++, t += step) {
+            for(var k = 0; k <= n; k++) {
```
Comment (emilykl) [inline src/traces/violin/calc.js]:
```suggestion
            for(var k = 0; k < cdi.density.length; k++) {
```

File: draftlogs/7581_fix.md [hunk 2]
```diff
@@ -0,0 +1 @@
+- Fix KDE sampling precision in violin trace to eliminate floating-point drift and prevent density underrun/overrun ([#7581](https://github.com/plotly/plotly.js/pull/7581))
```
Comment (emilykl) [inline draftlogs/7581_fix.md]: formatting

```suggestion
- Fix KDE sampling precision in violin trace to eliminate floating-point drift and prevent density underrun/overrun [[#7581](https://github.com/plotly/plotly.js/pull/7581)]
```

**Review by emilykl — APPROVED** [review]
@Koookadooo Two very minor suggestions (one is just draftlog formatting) otherwise LGTM! Thanks for your work on this.

**Comment by etpinard** [comment]
nice fix :clap:
