### PR TITLE
dispose delaunayMeadh on scatter3d toggle [fixes #399]

### LINKED ISSUE #399: Toggling visibility of scatter3d traces with surfaceaxis turned on does not work
To replicate, toggle the legend items of http://codepen.io/etpinard/pen/oxoRLJ

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz probably the easiest bug fix of all time.

### CODE REVIEW

**Comment by mdtusz** [comment]
Can't argue with that.
💃

File: src/traces/scatter3d/convert.js [hunk 1]
```diff
@@ -432,7 +432,7 @@ proto.dispose = function() {
         this.scatterPlot.dispose();
     }
     if(this.errorBars) {
-        this.scene.remove(this.errorBars);
+        this.scene.glplot.remove(this.errorBars);
```
Comment (etpinard) [inline src/traces/scatter3d/convert.js]: @mdtusz one more.
