### PR TITLE
Fix period positioned hover to work in different time zones as well as on grouped bars

### LINKED ISSUE #5841: Bars and unified hover location with half-years periods
This pen has oddly-positioned hovers: https://codepen.io/nicolaskruchten/pen/RwVZgBW?editors=0010

### PR DESCRIPTION
**Pull request by archmoj**
Fixes https://github.com/plotly/plotly.js/issues/5822#issuecomment-886413675 | cc: #5861 
Also closes #5841.

@plotly/plotly_js

### CODE REVIEW

File: src/components/fx/hover.js [hunk 1]
```diff
@@ -1993,19 +1993,33 @@ function getCoord(axLetter, winningPoint, fullLayout) {
...
+            var end = d[axLetter + 'End'];
+            var diff = end - start;
+            if(periodalignment === 'end') {
+                val += diff;
+            } else if(periodalignment === 'middle') {
+                val += diff / 2;
+            }
+        }
+
+        val = ax.d2c(val);
```
Comment (alexcjohnson) [inline src/components/fx/hover.js:2014]: @archmoj Can you explain why the previous code was timezone-dependent, and how this fixes it?

File: src/components/fx/hover.js [hunk 2]
```diff
@@ -1993,19 +1993,33 @@ function getCoord(axLetter, winningPoint, fullLayout) {
...
     }
 
-    var cd0 = winningPoint.cd[winningPoint.index];
-    if(cd0 && cd0.t && cd0.t.posLetter === ax._id) {
+    if(d && d.t && d.t.posLetter === ax._id) {
```
Comment (alexcjohnson) [inline src/components/fx/hover.js:2017]: This code has been around for ages but I'm just noticing it now and it confused the heck out of me: normally the `t` object only exists on the first entry in `cd` (that's why the var we extracted it from was called `cd0`) because it contains extra calculated info that applies to the whole trace. And at the `calc` step that's [true of box and violin too](https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/traces/box/calc.js#L278-L298). But then during the `plot` step it appears these traces [add `t` to all `cd` entries](https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/traces/box/plot.js#L172-L180) so that if you draw points, the one box the points are for will look like a whole trace to the reused scatter code with which we're drawing the points.

So yes, this works... but only due to a quirk of our drawing code and only for box and violin, so it feels fragile. Nonblocking, but when we need `t` we should really get it from `cd[0]`.

File: src/components/fx/hover.js (hunk 1 above)
Comment (archmoj) [reply src/components/fx/hover.js:2014]: The previous logic used start and end of period directly which appears to depend on the time zone.
But now we only use the difference between two which should not be impacted by time zone.
We will keep #5861 open until we could further investigate other time zone problems.

File: src/components/fx/hover.js (hunk 2 above)
Comment (archmoj) [reply src/components/fx/hover.js:2017]: What you suggesting here is renaming `d` back to `cd0`? Or I should simply add a comment above `cd0.d`?

Comment (alexcjohnson) [reply src/components/fx/hover.js:2017]: I'm saying instead of assuming box & violin will have `t` in every element of `cd` (`d` is `cd[winningPoint.index]` and `winningPoint.index` need not be zero) we should be using `cd[0].t`.

File: src/components/fx/hover.js (hunk 1 above)
Comment (alexcjohnson) [reply src/components/fx/hover.js:2014]: Ah ok, I think I understand it now. The previous one had the advantage of front-loading more of the calculation, so let's try and get back toward that. I _think_ what's going on is when you pull out the period with:
```js
var period = winningPoint[axLetter + 'Period'];
```
This is already in calcdata format - ie a number - so when we run `ax.d2c` on it we get the legacy convert-from-local-to-UTC behavior. But `val` is in data format - ie a  string - so it needs `ax.d2c`. So the right solution is to just change the one line:
```js
val = ax.d2c(period !== undefined ? period : val);
```
To:
```js
val = period !== undefined ? period : ax.d2c(val);
```

File: src/components/fx/hover.js (hunk 2 above)
Comment (archmoj) [reply src/components/fx/hover.js]: Addressed in https://github.com/plotly/plotly.js/pull/5864/commits/3e52b941be9b9e384a9c345bc2ab6a16076926fe

File: src/components/fx/hover.js (hunk 1 above)
Comment (archmoj) [reply src/components/fx/hover.js:2019]: Thanks for the hint. There was actually a problem in new code which is fixed now.
Unfortunately  trying `val = period !== undefined ? period : ax.d2c(val);` didn't pass the tests.
However `xStart` and `xEnd` are coming from the calc step so the changes should be fast.

File: .circleci/config.yml [hunk 3]
```diff
@@ -31,6 +31,35 @@ jobs:
...
+          command: date && npm run test-jasmine hover_label
+      - run:
+          name: Run hover_label test in Asia/Tokyo timezone
+          environment:
+            TZ: "Asia/Tokyo"
+          command: date && npm run test-jasmine hover_label
+      - run:
+          name: Run hover_label test in America/Toronto timezone
+          environment:
+            TZ: "America/Toronto"
```
Comment (archmoj) [inline .circleci/config.yml:60]: Do we need all these time zones to be tested?

File: src/components/fx/hover.js (hunk 1 above)
Comment (alexcjohnson) [reply src/components/fx/hover.js:2019]: Hmm OK - well, this seems to work so let's go with it. Thanks for investigating!

File: .circleci/config.yml (hunk 3 above)
Comment (alexcjohnson) [reply .circleci/config.yml:60]: It's pretty quick, might as well keep them all for now.

**Review by alexcjohnson — APPROVED** [review]
💃  Let's go!
