### PR TITLE
Bug null data

### LINKED ISSUE #271: Null data points on categorical axes should be ignored
See http://codepen.io/etpinard/pen/wMLEoO

At the moment, `null` data points on numerical axes are ignored whenever `connectgaps` is set to false. But, axes with `type` set to `category` stringify the `null` values as categories.

### PR DESCRIPTION
**Pull request by mdtusz**
Fixes #271.

Real short fix. I'm not too sure where best to put the tests for this one though so I created a new testfile. I'm happy to move them into an existing file if there is a suitable place though.

### CODE REVIEW

File: src/plots/cartesian/set_convert.js [hunk 1]
```diff
@@ -184,10 +184,13 @@ module.exports = function setConvert(ax) {
             // that aren't in the first etc.
             // TODO: sorting options - do the sorting
             // progressively here as we insert?
-            if(ax._categories.indexOf(v)===-1) ax._categories.push(v);
 
-            var c = ax._categories.indexOf(v);
-            return c===-1 ? constants.BADNUM : c;
+            if(v !== null && v !== undefined && ax._categories.indexOf(v) === -1){
```
Comment (etpinard) [inline src/plots/cartesian/set_convert.js]: nice, maybe we should make that standard: http://eslint.org/docs/rules/no-eq-null

File: src/plots/cartesian/set_convert.js [hunk 2]
```diff
@@ -184,10 +184,13 @@ module.exports = function setConvert(ax) {
...
+                ax._categories.push(v);
+                return ax._categories.length - 1;
```
Comment (etpinard) [inline src/plots/cartesian/set_convert.js]: Oh. I don't think this is right.

Because different traces can share categories, so the index of the incoming category here won't necessarily be the `length - 1`.

File: test/jasmine/tests/calcdata_test.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+            expect(gd.calcdata[0][1]).toEqual({ x: false, y: false});
+            expect(gd.calcdata[0][3]).toEqual({ x: false, y: false});
+        });
+
+        it('should exclude null and undefined points as categories when false', function() {
+            Plotly.plot(gd, [{ x: [1,2,3,undefined,5], y: [1,null,3,4,5] }], { xaxis: { type: 'category' }});
+
+            expect(gd.calcdata[0][1]).toEqual({ x: false, y: false});
+            expect(gd.calcdata[0][3]).toEqual({ x: false, y: false});
```
Comment (etpinard) [inline test/jasmine/tests/calcdata_test.js]: yeah man :tada:

File: src/plots/cartesian/set_convert.js (hunk 2 above)
Comment (mdtusz) [inline src/plots/cartesian/set_convert.js]: Ah good catch. I suppose that's kinda the whole point of categories...

**Comment by etpinard** [comment]
Awesome. I'm gonna jump on this branch to add an image test at some before the next release.

**Comment by mdtusz** [comment]
:+1:

**Comment by etpinard** [comment]
:dancer: for me
