### PR TITLE
fix reset camera buttons to work after switching projection between perspective and orthographic

### LINKED ISSUE #3596: Reset camera to default or the last saved position may break the plot after switching to a new projection type
After switching gl3d projection type, clicking reset camera may remove the scene!
But the plot would appear after clicking other modebar buttons e.g. pan/orbit.
[codepen](https://codepen.io/MojtabaSamimi/pen/eXZKzQ?editors=0010).

### PR DESCRIPTION
**Pull request by archmoj**
Fixes the issue described in #3596.
[codepen Before](https://codepen.io/MojtabaSamimi/pen/eXZKzQ?editors=0010).
[codepen After](https://codepen.io/MojtabaSamimi/pen/PLNadO?editors=0010).

fixes #3596

### CODE REVIEW

File: src/components/modebar/buttons.js [hunk 1]
```diff
@@ -347,15 +347,19 @@ function handleCamera3d(gd, ev) {
         var key = sceneId + '.camera';
         var scene = fullLayout[sceneId]._scene;
 
-        if(attr === 'resetDefault') {
+        if(attr === 'resetDefault' || attr === 'resetLastSave') {
             aobj[key] = Lib.extendDeep({}, scene.cameraInitial);
```
Comment (etpinard) [inline src/components/modebar/buttons.js]: Wouldn't it be easier to _just_ save keys `up`, `eye` and `center` in `scene.cameraInitial` instead of saving the all `scene.camera` keys and then doing this fancy footwork to get the correct `projection.type`?

In other words, do we really need a `cameraInitial` stash? Could we instead just use a "view" stash:

```js
scene.viewInitial = {
  up: {x: /**/, y: /**/, z: /**/},
  eye: {x: /**/, y: /**/, z: /**/},
  center: {x: /**/, y: /**/, z: /**/}
}
```

Comment (archmoj) [reply src/components/modebar/buttons.js]: Good call. 
Done in https://github.com/plotly/plotly.js/pull/3597/commits/9e1aa7af86a8dab6e807e8ddea8dca826031cc41.

File: src/components/modebar/buttons.js [hunk 2]
```diff
@@ -347,15 +347,19 @@ function handleCamera3d(gd, ev) {
         var key = sceneId + '.camera';
         var scene = fullLayout[sceneId]._scene;
 
+        if(attr === 'resetDefault' || attr === 'resetLastSave') {
+            aobj[key] = Lib.extendDeep({}, scene.viewInitial);
+
+            aobj[key].projection = {
```
Comment (etpinard) [inline src/components/modebar/buttons.js]: We shouldn't need this after 9e1aa7af86a8dab6e807e8ddea8dca826031cc41

Comment (etpinard) [reply src/components/modebar/buttons.js]: Actually, you'll need to tweak `aobj` / `key` logic. In the end, `aobj` should look like:

```js
aobj = {
  'scene.camera.up': {/**/},
  'scene.camera.eye': {/**/},
  'scene.camera.center': {/**/}
}
```

as opposed to

```js
aobj = {
  'scene.camera': {
    up: {/**/},
    eye: {/**},
    center: {/**}
  }
}
```

File: src/components/modebar/buttons.js [hunk 3]
```diff
@@ -348,10 +348,14 @@ function handleCamera3d(gd, ev) {
...
         if(attr === 'resetDefault' || attr === 'resetLastSave') {
-            aobj[key] = Lib.extendDeep({}, scene.viewInitial);
-
-            aobj[key].projection = {
-                type: (scene.camera._ortho) ? 'orthographic' : 'perspective'
+            aobj[key] = {
+                'up': scene.viewInitial.up,
+                'eye': scene.viewInitial.eye,
+                'center': scene.viewInitial.center,
+                'projection': {
```
Comment (etpinard) [inline src/components/modebar/buttons.js]: We shouldn't need to update `projection` at all, am I right?

Comment (archmoj) [reply src/components/modebar/buttons.js]: You are right. But in order to that we need to explicitly pass the current projection here.

Comment (etpinard) [reply src/components/modebar/buttons.js]: Ok, that's a bug then. Calling

```
Plotly.relayout('graph', 'scene.camera.up', {/**/})
```

should not change the projection type.

Comment (alexcjohnson) [reply src/components/modebar/buttons.js]: don't we just need to flatten it to `aobj[key + '.up'] = ...` etc?

**Comment by etpinard** [comment]
Nicely done :dancer:

File: src/components/modebar/buttons.js (hunk 3 above)
Comment (archmoj) [reply src/components/modebar/buttons.js]: Thanks @alexcjohnson & @etpinard.
Flattening was really helpful.

**Comment by archmoj** [comment]
> Nicely done
@etpinard If you don't mind, there is one more commit ready to push which help switching the projection to graph default.

File: src/components/modebar/buttons.js [hunk 4]
```diff
@@ -351,12 +353,18 @@ function handleCamera3d(gd, ev) {
...
             aobj[key + '.up'] = null;
             aobj[key + '.eye'] = null;
             aobj[key + '.center'] = null;
         }
+
+        var newOrtho = (scene.viewInitial.projection.type === 'orthographic');
+        var oldOrtho = scene.camera._ortho;
+
+        if(newOrtho !== oldOrtho) {
+            aobj[key + '.projection'] = scene.viewInitial.projection;
```
Comment (etpinard) [inline src/components/modebar/buttons.js]: Wait. Why do we need this?

File: test/jasmine/tests/gl3d_plot_interact_test.js [hunk 5]
```diff
@@ -1490,7 +1490,7 @@ describe('Test gl3d relayout calls', function() {
         .then(done);
     });
 
-    it('@gl should maintain projection type when resetCamera buttons clicked after switching projection type from perspective to orthographic', function(done) {
+    it('@gl resetCamera buttons should be able to reset projection type after switching projection type from perspective to orthographic', function(done) {
```
Comment (etpinard) [inline test/jasmine/tests/gl3d_plot_interact_test.js]: Why do you change your mind here?

Comment (archmoj) [reply test/jasmine/tests/gl3d_plot_interact_test.js]: Now that we could switch projections to initial projection I thought we may change this.
If the user is not happy with the changes made to the camera and wants to get back to initial/home view this allows that. [Codepen](https://codepen.io/MojtabaSamimi/pen/JzbRjb?editors=0010).

**Comment by etpinard** [comment]
> Now that we could switch projections to initial projection I thought we may change this.
If the user is not happy with the changes made to the camera and wants to get back to initial/home view this allows that.

I disagree. The reset camera buttons should reset only the attribute that can be changed via user interactions i.e. drag/scroll/clicking on modebar buttons. As we can't change the `projection.type` via user interactions (we need a `relayout` call here), it shouldn't be part of `viewInitial` and shouldn't be handled on modebar button clicks.

I'm voting for the version pre https://github.com/plotly/plotly.js/pull/3597/commits/8444b99579fa42834b2cf8ab45dffa865e31b584

File: src/components/modebar/buttons.js [hunk 6]
```diff
@@ -338,6 +338,8 @@ modeBarButtons.resetCameraLastSave3d = {
 function handleCamera3d(gd, ev) {
     var button = ev.currentTarget;
     var attr = button.getAttribute('data-attr');
+    if(attr !== 'resetLastSave' && attr !== 'resetDefault') return;
```
Comment (etpinard) [inline src/components/modebar/buttons.js]: When does this happen?

**Comment by etpinard** [comment]
Well earned :dancer: 

Thanks for following through from my comments.
