### PR TITLE
Waterfall connector.line.width react bug in mode between

### LINKED ISSUE #3787: Waterfalls reacting weirdly for connector line thickness
The following CodePen emulates the `react()` calls that the RCE emits: https://codepen.io/nicolaskruchten/pen/vMdPNp?editors=0010 ... basically it mutates the figure and returns it with the identity of the `data` array changed, in order to trigger the `react()` logic. This works everywhere except `connector.line.width` in waterfalls for some reason ...

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #3787.
[Codepen After](https://codepen.io/MojtabaSamimi/pen/ROMbwr?editors=0010).

@plotly/plotly_js 
cc: @nicolaskruchten

### CODE REVIEW

File: src/traces/waterfall/attributes.js [hunk 1]
```diff
@@ -96,7 +96,9 @@ module.exports = {
     connector: {
         line: {
             color: extendFlat({}, lineAttrs.color, {dflt: Color.defaultLine}),
-            width: lineAttrs.width,
+            width: extendFlat({}, lineAttrs.width, {
```
Comment (nicolaskruchten) [inline src/traces/waterfall/attributes.js]: does a similar fix need to be applied anywhere else in this trace? I haven't rigorously tested each attr, I just happened to test this one a lot due to our conversations around the line extensions etc :)

**Comment by etpinard** [comment]
Ha, Good catch from this block:

https://github.com/plotly/plotly.js/blob/4f7592e2ba7a64bd07e4ba5ce1ee4f1fdcf05940/src/traces/bar/plot.js#L41-L45

which can't be transferred to `waterfal/style.js`.

------------

Nicely done :dancer:
