### PR TITLE
Fix layout of centered hover info #2154

### LINKED ISSUE #2154: Hover tooltip positioned wrong in stacked barchart when number of bar is 1
my macbook screen resolution : 1680x1050
browser: firefox 56.0.2 (64-bit)
reproducible jsfiddle link : https://jsfiddle.net/o9fc44pg/1/
used library : https://cdn.plot.ly/plotly-latest.min.js
Is there any limit of tooltip label character length?
screenshot 
screen shot 2017-11-13 at 9 45 24 am

### PR DESCRIPTION
**Pull request by rmoestl**
This fixes #2154: when hover info (aka tooltip) is rendered in the center due to a lack of space left or right, the text overflowed the box and the secondary hove info (trace name) was hidden underneath the primary one.

Final solution:
2154_layout_centered-hover-info-final

Hint: part of the discussion took place in https://github.com/rmoestl/plotly.js/pull/1.

### CODE REVIEW

File: test/jasmine/tests/hover_label_test.js [hunk 1]
```diff
@@ -1109,6 +1109,96 @@ describe('hover info', function() {
...
+
+        function assertTopsAligned(elem1, elem2, msg) {
+            var elem1BB = elem1.getBoundingClientRect();
+            var elem2BB = elem2.getBoundingClientRect();
+
+            // Hint: toBeWithin tolerance is exclusive, hence a
+            // diff of exactly 1 would fail the test
+            var tolerance = 1.1;
+            expect(elem1BB.top - elem2BB.top).toBeWithin(0, tolerance, msg);
+        }
```
Comment (alexcjohnson) [inline test/jasmine/tests/hover_label_test.js]: Love these assert functions! They'd be good candidates for `assets/custom_assertions` but we can leave them here until someone else finds a use for them elsewhere.

File: test/jasmine/tests/hover_label_test.js [hunk 2]
```diff
@@ -1109,6 +1109,96 @@ describe('hover info', function() {
...
+
+        it('renders labels inside boxes', function(done) {
+            _hover(gd, 300, 150);
+
+            var nodes = ensureCentered(centeredHoverInfoNodes());
+            assertElemInside(nodes.primaryText, nodes.primaryBox, 'Primary text inside box');
+            assertElemInside(nodes.secondaryText, nodes.secondaryBox, 'Secondary text inside box');
+
+            done();
```
Comment (alexcjohnson) [inline test/jasmine/tests/hover_label_test.js]: do these test cases need to be async? Can't we just take out `done` from the function args and here?

**Comment by alexcjohnson** [comment]
@rmoestl looks great, beautiful tests. Just the one quick question https://github.com/plotly/plotly.js/pull/2440#discussion_r172212582 and then I think we're ready to 💃

File: test/jasmine/tests/hover_label_test.js (hunk 2 above)
Comment (rmoestl) [reply test/jasmine/tests/hover_label_test.js]: Good point. They don't need to be async. I'll go and change that.

**Comment by etpinard** [comment]
Great PR @rmoestl !

Thanks very much :tada:

**Comment by alexcjohnson** [comment]
Can we close #865 now too?

**Comment by alexcjohnson** [comment]
Interesting - looks like the text gets pushed up to avoid overlap with the orange bar, but the rect doesn't. @rmoestl since you've got your head wrapped around this part of the code, can you hunt this last bit down as well?
