### PR TITLE
Fixup misinterpreted clip-path by some programs after export

### LINKED ISSUE #5685: clip-path misinterpreted by some programs after export
We construct attributes like `clip-path="url('#clip4e1647xyplot')"` which normally works fine on its own, but for some reason recent versions of MS Word convert this to a broken reference `clip-path="url(##clip4e1647xyplot)"` (note the double `##`). If instead we omit the inner quotes `clip-path="url(#clip4e1647xyplot)"` Word appears to not mess with it, and it works fine.

We’ll have to do some testing to see if we can uniformly remove those extra quotes, especially in the presence of `<base>` tags (most commonly added by Angular) which force us to include the full page URL in the reference, not just the hash. But most documentation of the `clip-path` attribute does not include these quotes so hopefully it will be fine.

The fix is on this line:

https://github.com/plotly/plotly.js/blob/7588c9e057f5317332621e56933736eaece217b7/src/components/drawing/index.js#L1273

Which, if it works with a `baseUrl`, could just be simplified to:

```js
return 'url(' + baseUrl + '#' + localId)';
```

But if that has any problems we could remove the quotes only when `baseUrl` is falsy (`''`)

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5685.

@plotly/plotly_js

### CODE REVIEW

File: src/components/drawing/index.js [hunk 1]
```diff
@@ -1270,7 +1270,7 @@ function getFullUrl(localId, gd) {
 
     var context = gd._context;
     var baseUrl = context._exportedPlot ? '' : (context._baseUrl || '');
-    return 'url(\'' + baseUrl + '#' + localId + '\')';
+    return 'url(' + baseUrl + '#' + localId + ')';
```
Comment (alexcjohnson) [inline src/components/drawing/index.js:1273]: Per https://github.com/plotly/plotly.js/issues/5685#issuecomment-848883869 I think it's safer to keep the quotes when `baseUrl` is truthy (noting that the `_exportedPlot` condition appropriately clears it vs `context._baseUrl`).

**Review by alexcjohnson — APPROVED** [review]
💃 LGTM!
