### PR TITLE
Implement fgopacity, fgcolor & "overlay" fillmode for bars, fix bar legend and pattern with marker colorscale

### LINKED ISSUE #5285: Missing colors in bar legend having a colorscale
Originally reported in https://github.com/plotly/plotly.js/pull/1289#issuecomment-728275102 by @nitramwin
[Minimal codepen](https://codepen.io/MojtabaSamimi/pen/MWexGwp?editors=0010)

### LINKED ISSUE #5728: pattern bgcolor & fgcolor as well as overlay fillmode
Right now patterns basically replace fills, and I want to introduce a second mode where they overlay them instead:

* new attribute `marker.pattern.fillmode= enum(default=replace, overlay)`
* new attribute `marker.pattern.fgcolor`
* `replace` fillmode is the current behaviour:
    * `marker.pattern.bgcolor` is transparent
    * `marker.pattern.fgcolor` = `marker.color`
*  `overlay` fillmode will be:
    * `marker.pattern.bgcolor` = `marker.color`
    * `marker.pattern.fgcolor` will be set to to contrast the `bgcolor` using the same algo we use to contrast text on bars

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #5728 and fixes #5285.
Also fixes drawing bar `pattern` when the marker get a `colorscale`.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Behaviour looks pretty good at first glance! Will dig more tomorrow but nice job :)

**Comment by nicolaskruchten** [comment]
The legend items get hard to identify when the `size` goes up... could we offset the "+" and "." patterns so they're centered?

**Comment by nicolaskruchten** [comment]
I'm thinking that we need to tune things a little bit because for the same size/solidity, the different patterns feel quite different to my eye.

Also I'm thinking we need to either make the overlay semi-transparent or add `pattern.opacity` to make the patterns vibrate a little less strongly IMO.

**Comment by nicolaskruchten** [comment]
> I'm thinking that we need to tune things a little bit because for the same size/solidity, the different patterns feel quite different to my eye.

Well, playing with it a bit I can see this will be a rabbit-hole so let's leave this alone for now :)

so my asks are:

1. Can we fix the legend items for + and . patterns
2. Can we add `pattern.opacity` and set it to like 0.8 when fillmode=overlay, to make things a bit less intense?

**Comment by archmoj** [comment]
> 2. Can we add `pattern.opacity` and set it to like 0.8 when fillmode=overlay, to make things a bit less intense?

What about `pattern.fgopacity` which won't impact the background opacity?

**Comment by nicolaskruchten** [comment]
sounds good.

**Comment by nicolaskruchten** [comment]
oooh that's nice:

image

**Comment by archmoj** [comment]
> 1. Can we fix the legend items for + and . patterns

Good call. The scale for all shapes of legends is now reduced by https://github.com/plotly/plotly.js/pull/5733/commits/fd89e2311e7e3b95e218c950c1ccda0f771b77fc.

**Comment by nicolaskruchten** [comment]
OK, this behaviour is all good for me 🌟 

@alexcjohnson just need a dancer :)

File: src/components/drawing/index.js [hunk 1]
```diff
@@ -500,7 +529,8 @@ drawing.pattern = function(sel, gd, patternID, shape, bgcolor, fgcolor, size, so
                 'id': fullID,
                 'width': width + 'px',
                 'height': height + 'px',
-                'patternUnits': 'userSpaceOnUse'
+                'patternUnits': 'userSpaceOnUse',
+                'patternTransform': isLegend ? 'scale(0.7)' : ''
```
Comment (alexcjohnson) [inline src/components/drawing/index.js:533]: Can we adjust the size from the legend side, rather than detecting the legend inside here? Also do we need to scale down *all* these sizes? I'd rather we just restrict the maximum size to something we know will work, and perhaps when we have an array for pattern size just use the default size instead of the first one.

Comment (archmoj) [reply src/components/drawing/index.js:534]: Good calls.
See https://github.com/plotly/plotly.js/pull/5733/commits/5f5561f0269931b59081c665691696b953123a48, https://github.com/plotly/plotly.js/pull/5733/commits/a2a66e7d539859655db759361b79d79dea16fd7c and https://github.com/plotly/plotly.js/pull/5733/commits/69f91e2c3921667d5e6f5f434eddde842a71f49c.

File: src/components/drawing/index.js [hunk 2]
```diff
@@ -569,6 +600,13 @@ drawing.getPatternAttr = function(mp, i, dflt) {
     return mp;
 };
 
+drawing.getPatternLegendDim = function(mp, i, dflt) {
```
Comment (alexcjohnson) [inline src/components/drawing/index.js:603]: `i` is unused 😉

File: src/components/drawing/index.js (hunk 1 above)
Comment (alexcjohnson) [reply src/components/drawing/index.js:534]: Again though, do we need to scale down to 0.7 here? In the [legend style we already limit the size to 12](https://github.com/plotly/plotly.js/pull/5733/files#diff-3f7cb083e91b0a4c750484d81114195ba135277cb648d2b6751cdeaeacaffacfR369), can't we keep the same scale as on the graph, but if 12 is too big just reduce that limit?

File: src/components/drawing/index.js (hunk 2 above)
Comment (archmoj) [reply src/components/drawing/index.js]: Good eye. Fixed now.

File: src/components/drawing/index.js (hunk 1 above)
Comment (archmoj) [reply src/components/drawing/index.js]: Today in https://github.com/plotly/plotly.js/pull/5733/commits/38bd5ec0ea4a5ef7b6d9edbca822d64ca7bace81 I did try to avoid this scale reduction. But the problem is that the default size of 8 does not fit nicely in the legend icons and lose their identity.
So again in https://github.com/plotly/plotly.js/pull/5733/commits/178e0a608a2ffa37f111f8c86e97a042038eba37 I scaled down the patterns for icons using a greater ratio at 0.8.

Comment (nicolaskruchten) [reply src/components/drawing/index.js]: I think the current legend items are "ok" ... better than on master, and we can always tweak them a bit more later. I really do need to get this merged and released so unless there's a hard blocker/pathological case here, can we defer the remaining work @alexcjohnson ?

Comment (alexcjohnson) [reply src/components/drawing/index.js]: OK

**Review by alexcjohnson — APPROVED** [review]
💃

**Comment by archmoj** [comment]
The image test does not show a green light this branch at the moment.
While we updated flaky list on the master in #5737, let's see is we need to adjust it once again after the merge.
Merging...
