### PR TITLE
Correct gl2d and gl3d tick angles [fixes #119]

### LINKED ISSUE #119: tickangle is wrong units in scattergl
The units for `tickangle` is degrees when using `scatter`:

```
Plotly.plot(Tabs.fresh(), [{x:[1,2,3], y:[2,1,2], type:'scatter'}], {yaxis:{tickangle:-10}});
```

However, it switches to radians when using `scattergl`:

```
Plotly.plot(Tabs.fresh(), [{x:[1,2,3], y:[2,1,2], type:'scattergl'}], {yaxis:{tickangle:-10}});
```

This could be a bug in the underlying `gl-plot2d` library, it doesn't seem to specify what units are expected here.

Also, there is a test `gl2d_axes_labels` that does specify `tickangle: 45`, but it turns out that 45 radians looks visually similar to 45 degrees by coincidence, approximately 58 degrees to be more precise.  It does appear that this test's baseline "correct" image does have a 58 degree slant baked into it.

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz @cldougl

### CODE REVIEW

File: src/plots/gl2d/convert.js [hunk 1]
```diff
@@ -123,7 +123,9 @@ proto.merge = function(options) {
 
             this.tickEnable[i+j] = false;
             this.tickColor[i+j] = str2RGBArray((ax.tickfont || {}).color);
-            this.tickAngle[i+j] = (ax.tickangle === 'auto') ? 0 : -ax.tickangle;
+            this.tickAngle[i+j] = (ax.tickangle === 'auto') ?
+                0 :
+                Math.PI * -ax.tickangle / 180;
```
Comment (etpinard) [inline src/plots/gl2d/convert.js]: If you're like me, I find this way more explicit than having some degrees-to-radians lib function.

But, I'd be ok with adding a lib function if preferable.

Comment (cldougl) [inline src/plots/gl2d/convert.js]: I'm good w/ it here

**Comment by cldougl** [comment]
:dancer:
