### PR TITLE
Zoomscroll fix

### LINKED ISSUE #528: scrollZoom is incorrect on mouse scroll
broken since `1.10.0`

See: http://codepen.io/etpinard/pen/mPgWer

scroll zoom is correct on `mouseup` though.

### PR DESCRIPTION
**Pull request by mdtusz**
This pr fixes #528. There was a regression when the last remaining nested `<svg>` tags were removed, so that when zooming with a scroll, the transforms were incorrect.

**In brief:**
* add `Lib.getScale/Lib.setScale` similar to `Lib.getTranslate/Lib.setTranslate`
* scale the plot when zooming with a scroll, based on the mouse position
* add a mouse scroll event helper for tests - usage is `mouseEvent('scroll', 100, 100, { deltaX: 0, deltaY: -500 })`
* reduce the redraw time to 50ms - this makes the scroll zoom feel much snappier in my opinion, but we may need to raise it to something a bit higher if there's issues on other machines/browsers (something closer to 100ms or 200ms)
* added a super simple test for the scrolling - because `relayout` is called 50ms after the scroll is done, we need to "catch" the transformation (or alternatively we could use spies, but this seemed much simpler and will catch issues just the same)

### CODE REVIEW

File: test/jasmine/tests/lib_test.js [hunk 1]
```diff
@@ -890,6 +884,43 @@ describe('Test lib.js:', function() {
...
+
+            Lib.setScale(el, 30, 40);
+            expect(el.attr('transform')).toBe('scale(30, 40)');
+
+            Lib.setScale(el);
+            expect(el.attr('transform')).toBe('scale(1, 1)');
+
+            el.attr('transform', 'scale(0, 0); rotate(30)');
+            Lib.setScale(el, 30, 40);
+            expect(el.attr('transform')).toBe('rotate(30) scale(30, 40)');
```
Comment (etpinard) [inline test/jasmine/tests/lib_test.js]: nicely done.

File: src/lib/index.js [hunk 2]
```diff
@@ -483,6 +483,44 @@ lib.setTranslate = function(element, x, y) {
...
+    var re = /.*\bscale\((\d*\.?\d*)[^\d]*(\d*\.?\d*)[^\d].*/,
+        getter = element.attr ? 'attr' : 'getAttribute',
+        transform = element[getter]('transform') || '';
+
+    var translate = transform.replace(re, function(match, p1, p2) {
+        return [p1, p2].join(' ');
+    })
+    .split(' ');
+
+    console.log(translate);
```
Comment (etpinard) [inline src/lib/index.js]: :zap: please

File: src/lib/index.js [hunk 3]
```diff
@@ -449,12 +449,12 @@ lib.addStyleRule = function(selector, styleString) {
 
 lib.getTranslate = function(element) {
 
-    var re = /(\btranslate\()(\d*\.?\d*)([^\d]*)(\d*\.?\d*)([^\d]*)(.*)/,
+    var re = /.*\btranslate\((\d*\.?\d*)[^\d]*(\d*\.?\d*)[^\d].*/,
```
Comment (etpinard) [inline src/lib/index.js]: can you elaborate on this change (disclaimer I'm not Regex expert)?

File: src/plots/cartesian/dragbox.js [hunk 4]
```diff
@@ -347,7 +347,7 @@ module.exports = function dragBox(gd, plotinfo, x, y, w, h, ns, ew) {
     var scrollViewBox = [0, 0, pw, ph],
         // wait a little after scrolling before redrawing
         redrawTimer = null,
-        REDRAWDELAY = 300,
+        REDRAWDELAY = 50,
```
Comment (etpinard) [inline src/plots/cartesian/dragbox.js]: :+1: for making this smaller.

But, could you move this `REDRAWDELAY` value to `plots/cartesian/constants` so that power users can easily change it if they want slower redraw cycles.

File: src/plots/cartesian/dragbox.js [hunk 5]
```diff
@@ -608,19 +608,24 @@ module.exports = function dragBox(gd, plotinfo, x, y, w, h, ns, ew) {
...
                 var clipId = 'clip' + fullLayout._uid + subplots[i] + 'plot';
 
                 fullLayout._defs.selectAll('#' + clipId)
-                    .attr('transform', 'translate(' + clipDx + ', ' + clipDy + ')');
+                    .call(Lib.setTranslate, viewBox[0], viewBox[1])
+                    .call(Lib.setScale, 1 / xScaleFactor, 1 / yScaleFactor);
                 subplot.plot
-                    .attr('transform', 'translate(' + plotDx + ', ' + plotDy + ')');
+                    .call(Lib.setTranslate, plotDx, plotDy)
+                    .call(Lib.setScale, xScaleFactor, yScaleFactor);
```
Comment (etpinard) [inline src/plots/cartesian/dragbox.js]: nicely done.

File: src/plots/cartesian/dragbox.js [hunk 6]
```diff
@@ -601,32 +601,35 @@ module.exports = function dragBox(gd, plotinfo, x, y, w, h, ns, ew) {
             subplots = Object.keys(plotinfos);
 
         for(var i = 0; i < subplots.length; i++) {
+
             var subplot = plotinfos[subplots[i]],
+                clipId = 'clip' + fullLayout._uid + subplots[i] + 'plot',
```
Comment (etpinard) [inline src/plots/cartesian/dragbox.js]: This feels pretty frail.

Maybe we could store a subplot clip id in `fullLayout._plots[i].clipId`

File: src/plots/cartesian/dragbox.js [hunk 7]
```diff
@@ -601,32 +601,35 @@ module.exports = function dragBox(gd, plotinfo, x, y, w, h, ns, ew) {
...
-                subplot.plot
-                    .call(Lib.setTranslate, plotDx, plotDy)
-                    .call(Lib.setScale, xScaleFactor, yScaleFactor);
-            }
+
+            fullLayout._defs.selectAll('#' + clipId)
+                .call(Lib.setTranslate, clipDx, clipDy)
+                .call(Lib.setScale, 1 / xScaleFactor, 1 / yScaleFactor);
+
+            subplot.plot
```
Comment (etpinard) [inline src/plots/cartesian/dragbox.js]: great. Thanks for checking the fixed range case :beers:

File: src/lib/index.js (hunk 3 above)
Comment (mdtusz) [inline src/lib/index.js]: The regex is being used in `String.replace` which only substitutes the matched pattern - this just captures _everything_ in the string and allows replacement with only the two sections (the number values) it needs. I forgot to add a test for the case that it missed, but I'll add it now.

File: test/jasmine/tests/click_test.js [hunk 8]
```diff
@@ -711,6 +711,37 @@ describe('Test click interactions:', function() {
...
+        it('zooms in on scroll up', function() {
+
+            var plot = gd._fullLayout._plots.xy.plot;
+
+            mouseEvent('mousemove', 400, 250);
+            mouseEvent('scroll', 400, 250, { deltaX: 0, deltaY: -1000 });
+
+            var transform = plot.attr('transform');
+
+            console.log(transform);
```
Comment (etpinard) [inline test/jasmine/tests/click_test.js]: :zap: please.

File: src/plots/cartesian/dragbox.js (hunk 6 above)
Comment (mdtusz) [inline src/plots/cartesian/dragbox.js]: Agreed. I'm always hesitant to add _more_ onto fullLayout, but I suppose the clips _do_ get used fairly often.

File: src/lib/index.js (hunk 3 above)
Comment (etpinard) [inline src/lib/index.js]: Thanks!

File: test/jasmine/assets/mouse_event.js [hunk 9]
```diff
@@ -10,7 +10,14 @@ module.exports = function(type, x, y, opts) {
         fullOpts.buttons = opts.buttons;
     }
 
-    var el = document.elementFromPoint(x, y);
-    var ev = new window.MouseEvent(type, fullOpts);
+    var el = document.elementFromPoint(x, y),
+        ev;
+
+    if(type === 'scroll') {
+        ev = new window.WheelEvent('wheel', opts);
```
Comment (etpinard) [inline test/jasmine/assets/mouse_event.js]: :tada:

File: test/jasmine/tests/click_test.js [hunk 10]
```diff
@@ -711,6 +711,37 @@ describe('Test click interactions:', function() {
...
+                attr: function() {
+                    return transform;
+                }
+            };
+
+            var translate = Lib.getTranslate(mockEl),
+                scale = Lib.getScale(mockEl);
+
+            expect([translate.x, translate.y]).toBeCloseToArray([62.841, 99.483]);
+            expect([scale.x, scale.y]).toBeCloseToArray([1.221, 1.221]);
```
Comment (etpinard) [inline test/jasmine/tests/click_test.js]: :+1:

File: src/lib/index.js [hunk 11]
```diff
@@ -483,6 +483,44 @@ lib.setTranslate = function(element, x, y) {
     return transform;
 };
 
+lib.getScale = function(element) {
+
+    var re = /.*\bscale\((\d*\.?\d*)[^\d]*(\d*\.?\d*)[^\d].*/,
```
Comment (etpinard) [inline src/lib/index.js]: @mdtusz I was getting worried about all the regexes slowing down our code, but looks like they perform admirably (in comparison with `d3`): 

image

See [code](https://github.com/etpinard/plotly.js-benchmarks/blob/master/suites/set-translate/index.js);

**Comment by etpinard** [comment]
:dancer:
