### PR TITLE
Fix parcoords dimensions values & line coloring error with integer TypedArray

### LINKED ISSUE #3595: parcoords line coloring error with integer TypedArray
There seems to be an issue with specifying line color of a `parcoords` trace with an integer TypedArray. All of the values seem to be rounded to the min or max color value.

CodePen: https://codepen.io/jonmmease/pen/QoNgMe?editors=1010
```javascript
var trace = {
  type: 'parcoords',
  line: {
	  color: new Int32Array([0, 1, 2])
	  // color: new Float32Array([0, 1, 2])
          // color: [0, 1, 2]	  
  },
	
  dimensions: [{
    range: [1, 5],
    label: 'A',
    values: [1,4,3]
  }, {    
    range: [1,5],
    label: 'B',
    values: [3,1.5,2],
  }, {
    range: [1, 5],
    label: 'C',
    values: [2,4,1],
  }]
};

var data = [trace]

Plotly.plot('graphDiv', data, {}, {showSendToCloud: true});
```

When `line.color` is specified as a standard array or floating point TypedArray:

newplot 4

When `line.color` is specified as an integer TypedArray:
newplot 3

### PR DESCRIPTION
**Pull request by archmoj**
Fixes two issues reported & discovered in #3595 resulted from `integer` rounding errors. 
- [x] case of `color.line` typed arrays e.g. int32
- [x] case of `dimensions.values` typed arrays e.g. int32

@plotly_js
[Codepen Before](https://codepen.io/jonmmease/pen/QoNgMe?editors=1010).
[Codepen After](https://codepen.io/MojtabaSamimi/pen/GeZzjj?editors=1010).

### CODE REVIEW

**Comment by antoinerg** [comment]
Thanks for the fix @archmoj! It looks good to me :+1: 

I am wondering if we should add a parcoords mock with `line.color` as a typedArray to :lock: this down.

**Comment by archmoj** [comment]
@antoinerg thanks for the review & comment. I am not sure if we could make a JSON mock with typed arrays. So I may add a jasmine test.

**Comment by archmoj** [comment]
@antoinerg Please note that https://github.com/plotly/plotly.js/pull/3598/commits/e8cc760f642b932486638ef31a9cbf682926e06c is also added concerning my comment [here](https://github.com/plotly/plotly.js/issues/3595#issuecomment-469066307).

**Comment by antoinerg** [comment]
> I am not sure if we could make a JSON mock with typed arrays.

You're probably right :smile: Thanks for the jasmine tests!

I confirm this PR fix both issues in #3595 but I wonder why `coerce` isn't already doing the right thing and whether copying the `TypedArray` into an `Array` is avoidable. Therefore, I will leave it up to @etpinard to give you a dancer!

Nice work @archmoj

File: src/traces/parcoords/defaults.js [hunk 1]
```diff
@@ -49,6 +49,11 @@ function dimensionDefaults(dimensionIn, dimensionOut) {
     }
 
     var values = coerce('values');
+    if(!Array.isArray(values) && Lib.isArrayOrTypedArray(values)) {
+        // should convert typed arrays e.g. integers to real numbers
+        values = dimensionOut.values = Array.prototype.slice.call(values);
```
Comment (etpinard) [inline src/traces/parcoords/defaults.js]: Nop. Let's not do this during defaults to remain consistent with other typed-array-to-array blocks.

Move this to `parcoords/calc.js`.

File: src/traces/parcoords/defaults.js [hunk 2]
```diff
@@ -20,7 +20,12 @@ var maxDimensionCount = require('./constants').maxDimensionCount;
 var mergeLength = require('./merge_length');
 
 function handleLineDefaults(traceIn, traceOut, defaultColor, layout, coerce) {
+
     var lineColor = coerce('line.color', defaultColor);
+    if(!Array.isArray(lineColor) && Lib.isArrayOrTypedArray(lineColor)) {
+        // should convert typed arrays e.g. integers to real numbers
+        lineColor = traceOut.line.color = Array.prototype.slice.call(lineColor);
```
Comment (etpinard) [inline src/traces/parcoords/defaults.js]: same here.

**Comment by etpinard** [comment]
> but I wonder why `coerce` isn't already doing the right thing and whether copying the `TypedArray` into an `Array` is avoidable

because we don't want to do that in general. If we can keep typed arrays as typed array and handle them correct downstream, then we shouldn't convert them. See for example `ax.makeCalcdata` which is called by most trace modules:

https://github.com/plotly/plotly.js/blob/ecfa45a0f00b1b49c2fda9853e6ac69fa06c7a8f/src/plots/cartesian/set_convert.js#L516-L537

**Comment by etpinard** [comment]
> I am not sure if we could make a JSON mock with typed arrays.

See https://github.com/plotly/plotly.js/issues/913

File: src/traces/parcoords/defaults.js (hunk 1 above)
Comment (antoinerg) [reply src/traces/parcoords/defaults.js]: > If we can keep typed arrays as typed array and handle them correct downstream, then we shouldn't convert them.

That makes perfect sense!

File: src/traces/parcoords/calc.js [hunk 3]
```diff
@@ -39,3 +45,11 @@ function constHalf(len) {
     }
     return out;
 }
+
+function isTypedArray(a) {
```
Comment (etpinard) [inline src/traces/parcoords/calc.js]: No need for this. `Lib.isTypedArray` [is](https://github.com/plotly/plotly.js/blob/ecfa45a0f00b1b49c2fda9853e6ac69fa06c7a8f/src/lib/index.js#L29) a [thing](https://github.com/plotly/plotly.js/blob/ecfa45a0f00b1b49c2fda9853e6ac69fa06c7a8f/src/lib/array.js#L23-L26).

Comment (archmoj) [reply src/traces/parcoords/calc.js]: @etpinard Thanks for the note. 
Done in e577e49.

**Comment by etpinard** [comment]
Nicely done :dancer:
