### PR TITLE
Fix Non-Mapbox Scatter with text markers

### LINKED ISSUE #4110: scattermapbox: text not displayed when using non-mapbox predefined styles
In `scattermapbox`, when changing the style to a non-mapbox one, markers are still shown but not the text. Example Codepen: https://codepen.io/antoinerg/pen/ZgrYPw?editors=0010

Is that the expected behavior? Am I missing something?

### PR DESCRIPTION
**Pull request by baurt**
Fixes #4110 

Added `glyphs` as suggested in https://github.com/mapbox/mapbox-gl-js/issues/4808

Any font from [openmaptiles/fonts](https://github.com/openmaptiles/fonts/blob/gh-pages/fontstacks.json) is acceptable to use as the `textfont`.

### CODE REVIEW

**Comment by baurt** [comment]
Not sure why the baselines failed. Only `scattermapbox`, `mapbox.constants` and `scatter.text_defaults` were modified, but `scatter.text_defaults` is only used with scatter type plots.

File: src/traces/scatter/text_defaults.js [hunk 1]
```diff
@@ -8,10 +8,12 @@ var Lib = require('../../lib');
...
     opts = opts || {};
-
     coerce('textposition');
-    Lib.coerceFont(coerce, 'textfont', layout.font);
-
+    if(opts.font) {
+        Lib.coerceFont(coerce, 'textfont', opts.font);
+    } else {
+        Lib.coerceFont(coerce, 'textfont', layout.font);
+    }
```
Comment (archmoj) [inline src/traces/scatter/text_defaults.js:16]:
```suggestion
    Lib.coerceFont(coerce, 'textfont', opts.font || layout.font);
```

File: src/traces/scattermapbox/defaults.js [hunk 2]
```diff
@@ -66,7 +66,14 @@ module.exports = function supplyDefaults(traceIn, traceOut, defaultColor, layout
...
 
     if(subTypes.hasText(traceOut)) {
-        handleTextDefaults(traceIn, traceOut, layout, coerce, {noSelect: true});
+        handleTextDefaults(traceIn, traceOut, layout, coerce,
+            {noSelect: true,
+                font: {
+                    family: 'Open Sans Regular',
+                    size: layout.font.size,
+                    color: layout.font.color
+                }
```
Comment (archmoj) [inline src/traces/scattermapbox/defaults.js:75]:
```suggestion
                font: layout.font
```

**Comment by archmoj** [comment]
> 

> Not sure why the baselines failed. Only `scattermapbox`, `mapbox.constants` and `scatter.text_defaults` were modified, but `scatter.text_defaults` is only used with scatter type plots.

Thanks very much for the PR.

Considering a bug in our image test system we need to preserve the order of baseline creation in parallel runs. 
For non `mapbox` baseline we suggest to use `zz-` at the start of mock & baseline names.
But since you added a new `mapbox` mock in this PR and we want to allow some tolerance for `mapbox`, you need to download (from [here](https://output.circle-artifacts.com/output/job/b1582c90-318c-4d1d-bd72-61391258a629/artifacts/0/baselines.tar
) & replace these new baselines inside `test/image/baseline` folder.
That should help tests go green.
Thank you!

File: src/traces/scatter/text_defaults.js (hunk 1 above)
Comment (baurt) [reply src/traces/scatter/text_defaults.js]: Makes sense. Updated.

File: src/plots/mapbox/constants.js [hunk 3]
```diff
@@ -224,7 +231,7 @@ module.exports = {
...
         'ctrl-attrib.mapboxgl-compact:hover': 'padding: 2px 24px 2px 4px; visibility: visible; margin-top: 6px;',
-        'ctrl-attrib.mapboxgl-compact::after': 'content: ""; cursor: pointer; position: absolute; background-image: url(\'data:image/svg+xml;charset=utf-8,%3Csvg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"%3E %3Cpath fill="%23333333" fill-rule="evenodd" d="M4,10a6,6 0 1,0 12,0a6,6 0 1,0 -12,0 M9,7a1,1 0 1,0 2,0a1,1 0 1,0 -2,0 M9,10a1,1 0 1,1 2,0l0,3a1,1 0 1,1 -2,0"/%3E %3C/svg%3E\'); background-color: rgba(255, 255, 255, 0.5); width: 24px; height: 24px; box-sizing: border-box; border-radius: 12px;',
+        'ctrl-attrib.mapboxgl-compact::after': 'content: ""; cursor: pointer; position: absolute; background-image: url(\'data:image/svg+xml;charset=utf-8,%3Csvg viewBox="0 0 20 20" xmlns="https://www.w3.org/2000/svg"%3E %3Cpath fill="%23333333" fill-rule="evenodd" d="M4,10a6,6 0 1,0 12,0a6,6 0 1,0 -12,0 M9,7a1,1 0 1,0 2,0a1,1 0 1,0 -2,0 M9,10a1,1 0 1,1 2,0l0,3a1,1 0 1,1 -2,0"/%3E %3C/svg%3E\'); background-color: rgba(255, 255, 255, 0.5); width: 24px; height: 24px; box-sizing: border-box; border-radius: 12px;',
```
Comment (archmoj) [inline src/plots/mapbox/constants.js:234]: For `svg` we should keep `http://www.w3.org/2000/svg` no `https`.

File: src/plots/mapbox/constants.js [hunk 4]
```diff
@@ -47,7 +47,8 @@ var stylesNonMapbox = {
             source: 'plotly-osm-tiles',
             minzoom: 0,
             maxzoom: 22
-        }]
+        }],
+        glyphs: 'http://fonts.openmaptiles.org/{fontstack}/{range}.pbf'
```
[the remark this answers is not in the document]
Comment (baurt) [reply src/plots/mapbox/constants.js]: Definitely, that was just a copypasta. Updated.

File: src/plots/mapbox/constants.js [hunk 5]
```diff
@@ -240,9 +247,9 @@ module.exports = {
...
... -9.25,9.25 0,5.1 4.15,9.25 9.25,9.25 5.1,0 9.25,-4.15 9.25,-9.25 0,-5.11 -4.14,-9.25 -9.25,-9.25 z m 4.39,11.53 c -1.93,1.93 -4.78,2.31 -6.7,2.31 -0.7,0 -1.41,-0.05 -2.1,-0.16 0,0 -1.02,-5.64 2.14,-8.81 0.83,-0.83 1.95,-1.28 3.13,-1.28 1.27,0 2.49,0.51 3.39,1.42 1.84,1.84 1.89,4.75 0.14,6.52 z" style="opacity:0.9;fill:%23ffffff;enable-background:new" class="st0"/%3E%3Cpath d="M 10.5,-0.01 C 4.7,-0.01 0,4.7 0,10.49 c 0,5.79 4.7,10.5 10.5,10.5 5.8,0 10.5,-4.7 10.5,-10.5 C 20.99,4.7 16.3,-0.01 10.5,-0.01 Z m 0,19.75 c -5.11,0 -9.25,-4.15 -9.25,-9.25 0,-5.1 4.14,-9.26 9.25,-9.26 5.11,0 9.25,4.15 9.25,9.25 0,5.13 -4.14,9.26 -9.25,9.26 z" style="opacity:0.35;enable-background:new" class="st1"/%3E%3Cpath d="M 14.74,6.25 C 12.9,4.41 9.98,4.35 8.23,6.1 5.07,9.27 6.09,14.91 6.09,14.91 c 0,0 5.64,1.02 8.81,-2.14 C 16.64,11 16.59,8.09 14.74,6.25 Z m -2.27,4.09 -0.91,1.87 -0.9,-1.87 -1.86,-0.91 1.86,-0.9 0.9,-1.87 0.91,1.87 1.86,0.9 z" style="opacity:0.35;enable-background:new" class="st1"/%3E%3Cpolygon points="11.56,12.21 10.66,10.34 8.8,9.43 10.66,8.53 11.56,6.66 12.47,8.53 14.33,9.43 12.47,10.34 " style="opacity:0.9;fill:%23ffffff;enable-background:new" class="st0"/%3E%3C/g%3E%3C/svg%3E\')'
```
Comment (archmoj) [inline src/plots/mapbox/constants.js:250]: Also here let's revert the change for `svg`:
For `svg` we should keep `http://www.w3.org/2000/svg` no `https`.

File: src/plots/mapbox/constants.js [hunk 6]
```diff
@@ -240,9 +247,9 @@ module.exports = {
...
...47L83.04,14.47z"/%3E %3Cpath class="st0" style="opacity:0.9; fill: %23FFFFFF; enable-background: new;" d="M10.5,1.24c-5.11,0-9.25,4.15-9.25,9.25s4.15,9.25,9.25,9.25s9.25-4.15,9.25-9.25 C19.75,5.38,15.61,1.24,10.5,1.24z M14.89,12.77c-1.93,1.93-4.78,2.31-6.7,2.31c-0.7,0-1.41-0.05-2.1-0.16c0,0-1.02-5.64,2.14-8.81 c0.83-0.83,1.95-1.28,3.13-1.28c1.27,0,2.49,0.51,3.39,1.42C16.59,8.09,16.64,11,14.89,12.77z"/%3E %3Cpath class="st1" style="opacity:0.35; enable-background:new;" d="M10.5-0.01C4.7-0.01,0,4.7,0,10.49s4.7,10.5,10.5,10.5S21,16.29,21,10.49C20.99,4.7,16.3-0.01,10.5-0.01z M10.5,19.74c-5.11,0-9.25-4.15-9.25-9.25s4.14-9.26,9.25-9.26s9.25,4.15,9.25,9.25C19.75,15.61,15.61,19.74,10.5,19.74z"/%3E %3Cpath class="st1" style="opacity:0.35; enable-background:new;" d="M14.74,6.25C12.9,4.41,9.98,4.35,8.23,6.1c-3.16,3.17-2.14,8.81-2.14,8.81s5.64,1.02,8.81-2.14 C16.64,11,16.59,8.09,14.74,6.25z M12.47,10.34l-0.91,1.87l-0.9-1.87L8.8,9.43l1.86-0.9l0.9-1.87l0.91,1.87l1.86,0.9L12.47,10.34z"/%3E %3Cpolygon class="st0" style="opacity:0.9; fill: %23FFFFFF; enable-background: new;" points="14.33,9.43 12.47,10.34 11.56,12.21 10.66,10.34 8.8,9.43 10.66,8.53 11.56,6.66 12.47,8.53 "/%3E%3C/g%3E%3C/svg%3E\');'
```
Comment (archmoj) [inline src/plots/mapbox/constants.js:253]: Also here `https` > `http`.

File: draftlogs/6652_fix.md [hunk 7]
```diff
@@ -0,0 +1 @@
+fix text markers on non-mapbox styled maps [[#6652](https://github.com/plotly/plotly.js/pull/6652)]
```
Comment (archmoj) [inline draftlogs/6652_fix.md:1]:
```suggestion
 - fix text markers on non-mapbox styled maps [[#6652](https://github.com/plotly/plotly.js/pull/6652)], with thanks to @baurt for the contribution!
```

File: src/traces/scattermapbox/defaults.js (hunk 2 above)
Comment (baurt) [reply src/traces/scattermapbox/defaults.js:75]: I tried to not change this, but couldn't get it to work with the glyphs. If you make this change, you get:
image

The reason that I found was because `fontstack` in the glyphs key ends up being the entire family default. I'm not entirely sure where that gets set. Also, the font needs to be one of the items in [openmaptiles/fonts](https://github.com/openmaptiles/fonts/blob/gh-pages/fontstacks.json?rgh-link-date=2023-06-27T21%3A59%3A52Z), otherwise, you get a 404.

File: src/plots/mapbox/constants.js (hunk 3 above)
Comment (baurt) [reply src/plots/mapbox/constants.js]: updated

File: src/plots/mapbox/constants.js (hunk 5 above)
Comment (baurt) [reply src/plots/mapbox/constants.js]: Reverted.

File: src/traces/scattermapbox/defaults.js (hunk 2 above)
Comment (archmoj) [reply src/traces/scattermapbox/defaults.js:75]: Thanks for the note.
Let's add a comment and a function to handle cases that `layout.font.family` is not found in that list.
```js
var supportedFonts = [
    'Metropolis Black Italic',
    'Metropolis Black',
    'Metropolis Bold Italic',
    'Metropolis Bold',
    'Metropolis Extra Bold Italic',
    'Metropolis Extra Bold',
    'Metropolis Extra Light Italic',
    'Metropolis Extra Light',
    'Metropolis Light Italic',
    'Metropolis Light',
    'Metropolis Medium Italic',
    'Metropolis Medium',
    'Metropolis Regular Italic',
    'Metropolis Regular',
    'Metropolis Semi Bold Italic',
    'Metropolis Semi Bold',
    'Metropolis Thin Italic',
    'Metropolis Thin',
    'Open Sans Bold Italic',
    'Open Sans Bold',
    'Open Sans Extra Bold Italic',
    'Open Sans Extra Bold',
    'Open Sans Italic',
    'Open Sans Light Italic',
    'Open Sans Light',
    'Open Sans Regular',
    'Open Sans Semibold Italic',
    'Open Sans Semibold',
    'Klokantech Noto Sans Bold',
    'Klokantech Noto Sans CJK Bold',
    'Klokantech Noto Sans CJK Regular',
    'Klokantech Noto Sans Italic',
    'Klokantech Noto Sans Regular'
];
```
then
```js
                font: {
                    family: supportedFonts.indexOf(layout.font.family) !== -1 ? layout.font.family : 'Open Sans Regular',
                    size: layout.font.size,
                    color: layout.font.color
                }

Comment (baurt) [reply src/traces/scattermapbox/defaults.js]: Updated.
