### PR TITLE
fix #2633 - make sure we have a grid before attaching it to layoutOut

### LINKED ISSUE #2633: 1.37.x doesn't ignore `layout.grid: true` during defaults
The following chart  https://codepen.io/__proto__/pen/NMBpyY
 renders fine in Plotly.js with CDN version up to  [1.36.0](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.31.0/plotly.js) but fails in the latest release [1.37.0](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.37.0/plotly.js)

```
Uncaught TypeError: Cannot read property 'x' of undefined
    at handlePositionDefaults (VM10186 plotly.js:132985)
    at Object.supplyLayoutDefaults (VM10186 plotly.js:132829)
    at Object.plots.supplyLayoutModuleDefaults (VM10186 plotly.js:144174)
    at Object.plots.supplyDefaults (VM10186 plotly.js:143178)
    at Object.exports.plot (VM10186 plotly.js:121060)
    at Object.exports.newPlot (VM10186 plotly.js:121496)
    at VM9694 pen.js:278
```
image

I didn't see any release notes  for 1.37 so submitting this here in case.

### PR DESCRIPTION
**Pull request by alexcjohnson**
cc @etpinard a quick one - the key is attaching `gridOut` to `layoutOut` after [this short-circuit return](https://github.com/plotly/plotly.js/blob/2d84a8fba7aa27f36ff3c61e0e07616ab12cfd66/src/components/grid/index.js#L213)

### CODE REVIEW

File: test/jasmine/tests/plots_test.js [hunk 1]
```diff
@@ -908,6 +908,25 @@ describe('grids', function() {
         });
     }
 
+    it('does not barf on invalid grid objects', function(done) {
```
Comment (etpinard) [inline test/jasmine/tests/plots_test.js]: Nice!

Can you also check that `Plotly.validate([], {grid: true})` does the right thing? It barfs too on master.

Comment (alexcjohnson) [reply test/jasmine/tests/plots_test.js]: > Can you also check that `Plotly.validate([], {grid: true})` does the right thing?

good call -> https://github.com/plotly/plotly.js/pull/2638/commits/09ee26e0cf5dcf09b53b7dc3ea787c34c57407b2

**Comment by etpinard** [comment]
Nicely done :dancer:
