### PR TITLE
fix regression in lib/clean_number (alternate)

### LINKED ISSUE #1183: certain data input strings lead to broken plots.
http://codepen.io/bpostlethwaite/pen/rWyvgV

This effects plots out in the wild. 

@alexcjohnson @etpinard @chriddyp

### PR DESCRIPTION
**Pull request by etpinard**
fixes #1183

An alternate take on #1184

### CODE REVIEW

File: test/jasmine/tests/lib_test.js [hunk 1]
```diff
@@ -1522,7 +1522,12 @@ describe('Test lib.js:', function() {
                 ['-100.001', -100.001],
                 ['  $4.325  #%\t', 4.325],
                 [' " #1" ', 1],
-                [' \'\n \r -9.2e7   \t\' ', -9.2e7]
+                [' \'\n \r -9.2e7   \t\' ', -9.2e7],
+                ['1,690,000', 1690000],
+                ['1 690 000', 1690000],
```
Comment (etpinard) [inline test/jasmine/tests/lib_test.js]: @alexcjohnson 

From https://en.wikipedia.org/wiki/Decimal_mark

image

Comment (etpinard) [inline test/jasmine/tests/lib_test.js]: so maybe we should also include `'` and `-` (or is that a `\cdot`)?

File: test/jasmine/tests/lib_test.js [hunk 2]
```diff
@@ -1522,7 +1522,12 @@ describe('Test lib.js:', function() {
...
+                ['2 2', 22],
```
Comment (alexcjohnson) [inline test/jasmine/tests/lib_test.js]: Oh good call - `'1 690 000'` will show up. `'2 2'` looks weird, and likely to be a parsing error, but I don't see how we can distinguish it from legitimate spaces in numbers.

File: src/lib/clean_number.js [hunk 3]
```diff
@@ -16,14 +16,18 @@ var BADNUM = require('../constants/numerical').BADNUM;
...
  * cleanNumber: remove common leading and trailing cruft
  * Always returns either a number or BADNUM.
  */
 module.exports = function cleanNumber(v) {
     if(typeof v === 'string') {
-        v = v.replace(FRONTJUNK, '').replace(ENDJUNK, '');
+        v = v
+            .replace(FRONTJUNK, '')
+            .replace(ENDJUNK, '')
+            .replace(GLOBALJUNK, '');
```
Comment (alexcjohnson) [inline src/lib/clean_number.js]: The perf tests I did when playing with dates make me think it'll be faster to turn this into a single regex, but we should test that intuition, since this is a very hot path.

Also do we really want to allow any and all internal whitespace? Including line breaks and tabs? Or can we do just regular spaces?

Comment (etpinard) [inline src/lib/clean_number.js]: > The perf tests I did when playing with dates make me think it'll be faster to turn this into a single regex

Good call. I'll update this.

> Also do we really want to allow any and all internal whitespace?

Just `' '` is probably enough. It is also what we used to do here:

https://github.com/plotly/plotly.js/pull/1078/files#diff-9664b6a57e7771275ffd0c8805ea5917L30

File: test/jasmine/tests/lib_test.js [hunk 4]
```diff
@@ -1522,7 +1522,12 @@ describe('Test lib.js:', function() {
...
+                ['$5,162,000.00', 5162000],
+                [' $1,410,000.00 ', 1410000],
```
Comment (chriddyp) [inline test/jasmine/tests/lib_test.js]: another one `" -   "` to whatever it was before

**Comment by alexcjohnson** [comment]
I'd say 💃  to this one, and close #1184
