### PR TITLE
fix: Update config diff check method to handle nested arrays

### LINKED ISSUE #7572: [BUG]: Plotly.react with config that includes modeBarButtons broken in v3.1.1
### Description
With 3.1.1 using `Plotly.react` with a `config` object that has a `modeBarButtons` property on an already existing plot freezes the browser tab, spikes CPU Usage and consumes multiple GB of memory pretty quickly

### Steps to reproduce
[CodePen with reproducer](https://codepen.io/WeisSebastian/pen/YPwZeMJ)
Clicking the `Trigger plotly react` button is triggering the issue.

### Notes
This seems to be a regression in version 3.1.1, it works in 3.1.0 without issues.
When using WebGL plots, many `WARNING: Too many active WebGL contexts. Oldest context will be lost.` warnings are printed to the console (not visible in code pen, but visible when run locally). I'd assume it's some kind of infinite loop/recursion issue.
The error is present when using non WebGL plot types and the actual `modeBarButtons` added do not matter, it even happens with an empty `modeBarButtons` array (see example)

### PR DESCRIPTION
**Pull request by camdecoster**
### Description

Update config diff check to handle nested arrays.

Closes #7572.

### Changes

- Linting/formatting
- Update config diff check method to handle nested arrays
- Move method to helpers file
- Add tests for method

### Testing

- Be on master
- Run this mock in plotly.js DevTools:
  ```json
  {
    "data": [
      {
      "error_x": {
        "array": [100000.0, 100000.0, 100000.0],
        "type": "data",
        "visible": true
      },
      "type": "scatter",
      "x": [1554370371547.085, 1554370471547.085, 1554370571547.085],
      "y": [6, 10, 2]
      }
    ],
    "layout": {
      "xaxis": {
      "type": "date"
      }
    },
    "config": {
      "modeBarButtons": [[]]
    }
  }
  ```
- Be aware that entering the next command will cause an infinite recursive loop, so add a debugger statement in `react` before you do to avoid crashing your browser/computer
- Call `react` from the browser DevTools console with the following command:
  ```
  Plotly.react(gd, gd.data, gd.layout, { modeBarButtons: [ [] ] })
  ```
- Click the debugger continue button a number of times and note that it just keeps happening
- Switch to this branch
- Run through the same process again
- Click the debugger continue button and note that it only runs through once

### Notes

- The current diff method doesn't handle nested arrays properly, so the diff check will always return true in this case
- It didn't cause a problem before because the old code ran through `react` once and that was it. The new code can make a call to `react` recursively, which is triggered by the above example.
- It only happens with the `modeBarButtons` config option because that's the only one that takes a nested array as a value

### TODO
- [x] Add draftlog

### CODE REVIEW

File: src/plot_api/helpers.js [hunk 1]
```diff
@@ -475,6 +475,7 @@ exports.hasParent = function (aobj, attr) {
     return false;
 };
 
+const AX_LETTERS = ['x', 'y', 'z'];
```
Comment (emilykl) [inline src/plot_api/helpers.js]: put at top of file perhaps? I would normally expect constants not inside a function to be defined at the top of the file.

File: src/plot_api/helpers.js [hunk 2]
```diff
@@ -507,3 +507,35 @@ exports.clearAxisTypes = function (gd, traces, layoutUpdate) {
...
 };
+
+/**
+ * Check if a collection (object or array) has changed given two versions of
+ * the collection: old and new.
+ *
+ * @param {Object|Array} oldCollection: Old version of collection to compare
+ * @param {Object|Array} newCollection: New version of collection to compare
+ */
+const hasCollectionChanged = (oldCollection, newCollection) => {
```
Comment (emilykl) [inline src/plot_api/helpers.js]: just a nit, but I would expect this function to be called something slightly more general like `areObjectsEqual()` since the function itself doesn't care whether `oldCollection` and `newCollection` are versions of the same object or not; that's a matter of how the function is used.

File: src/plot_api/helpers.js [hunk 3]
```diff
@@ -507,3 +507,35 @@ exports.clearAxisTypes = function (gd, traces, layoutUpdate) {
...
+        for (let i = 0; i < oldCollection.length; i++) {
+            const oldVal = oldCollection[i];
+            const newVal = newCollection[i];
+            if (oldVal !== newVal) return isArrayOrObject(oldVal, newVal) ? hasCollectionChanged(oldVal, newVal) : true;
+        }
+    } else {
+        if (Object.keys(oldCollection).length !== Object.keys(newCollection).length) return true;
+
+        for (const k in oldCollection) {
+            if (k.startsWith('_')) return false;
```
Comment (emilykl) [inline src/plot_api/helpers.js]: this seems wrong, am I missing something? Is it supposed to be `if (k.startsWith('_')) continue;` ?

**Comment by emilykl** [comment]
@camdecoster Infinite loop is resolved, but I am not able to update the modebar buttons successfully by calling `Plotly.react()`.

This is the line I am running in the browser console: 
```js
Plotly.react(gd, gd.data, gd.layout, { modeBarButtons: [['zoom2d', 'pan2d'], ['autoScale2d', 'resetScale2d']] });
```

I would expect to see new buttons show up in the modebar but I see nothing. I am also seeing that `hasCollectionChanged()` seems to return `false` in that case but I haven't dug deeper than that.

**Comment by emilykl** [comment]
Also have you been able to learn anything about the intentions behind [this test](https://github.com/plotly/plotly.js/blob/7d51eddbffc1f8e9bc346947d40005694d15db92/test/jasmine/tests/transition_test.js#L519)? Unclear whether it was deliberately forbidden for a philosophical reason, or just because it was complicated to implement.

File: src/plot_api/helpers.js (hunk 3 above)
Comment (emilykl) [reply src/plot_api/helpers.js]: Wait, looking closely this whole loop is problematic; it should only ever return `true` from within the loop. Line 535 will return `false` sometimes and short-circuit the whole loop if `hasCollectionChanged(oldVal, newVal)` returns `false`.

File: src/plot_api/helpers.js (hunk 1 above)
Comment (camdecoster) [reply src/plot_api/helpers.js]: Can do.

File: src/plot_api/helpers.js (hunk 2 above)
Comment (camdecoster) [reply src/plot_api/helpers.js]: I was trying to be generic with the term "collection" since you could be passing in an object or an array, but we could go further as you suggest. Would `areCollectionsEqual` be acceptable?

File: src/plot_api/helpers.js (hunk 3 above)
Comment (camdecoster) [reply src/plot_api/helpers.js]: Good catch! I did a poor job of converting this loop from it's previous iteration. I updated it to only return when `true`.

**Comment by camdecoster** [comment]
> Also have you been able to learn anything about the intentions behind [this test](https://github.com/plotly/plotly.js/blob/7d51eddbffc1f8e9bc346947d40005694d15db92/test/jasmine/tests/transition_test.js#L519)? Unclear whether it was deliberately forbidden for a philosophical reason, or just because it was complicated to implement.

I've only looked at it to understand why it was failing. In this case, it was because of the bad loop conversion. I'll see if I can understand it a bit better and report back.

**Comment by emilykl** [comment]
> I've only looked at it to understand why it was failing. In this case, it was because of the bad loop conversion. I'll see if I can understand it a bit better and report back.

I ask because the wording of the test case ("should not try to transition when the *config* has changed") seems to directly oppose the functionality you've added (making sure a transition happens during `react()` when the config has changed). I don't see any reason why that's a problem, but the person who added the test originally apparently thought that shouldn't happen.

File: src/plot_api/helpers.js (hunk 2 above)
Comment (emilykl) [reply src/plot_api/helpers.js]: yes, `areCollectionsEqual` (or maybe `collectionsAreEqual`?) sounds good to me 👍 

Actually, one related question — what is the reason for ignoring keys starting with an underscore? Is that due to a JavaScript implementation detail, or a Plotly.js one? Maybe that should be captured in the function name (since it's a very particular definition of equality)

**Comment by camdecoster** [comment]
> I ask because the wording of the test case ("should not try to transition when the _config_ has changed") seems to directly oppose the functionality you've added (making sure a transition happens during `react()` when the config has changed). I don't see any reason why that's a problem, but the person who added the test originally apparently thought that shouldn't happen.

Okay, so config changes shouldn't be animated per [this](https://github.com/plotly/plotly.js/blob/7d51eddbffc1f8e9bc346947d40005694d15db92/src/plot_api/plot_api.js#L2692-L2695) comment. The second call to `react` that I added handles the situation where both the config and some attribute that should be animated were changed. On the second pass through, the config isn't changing, so that should trigger the transition (if one should occur).

So, the test is there to make sure no transitions happen when a config change occurs. This might actually add a new feature that didn't exist before the changes to `react` in #7475: now you can pass in changes to the config and other transition-triggering changes and they should both get handled.

File: src/plot_api/helpers.js (hunk 2 above)
Comment (camdecoster) [reply src/plot_api/helpers.js]: That's a plotly.js detail, but it's also a JavaScript convention. Variables that start with underscore are labeled as such because they are meant to be used internally by the library. So, you wouldn't see a user changing those values, hence they can be ignored.

**Comment by camdecoster** [comment]
> Infinite loop is resolved, but I am not able to update the modebar buttons successfully by calling `Plotly.react()`.

This was a consequence of the loop logic error. I tried it after the fix and it worked. Could you try again with the latest changes?

**Comment by emilykl** [comment]
@camdecoster Thanks for the clear explanation, that all makes sense.

I've tested again and it seems to be working as expected.

**Review by emilykl — APPROVED** [review]
LGTM. Maybe add a few more Jasmine tests for `collectionsAreEqual()` if you have the bandwidth, but not required.

File: test/jasmine/tests/plot_api_test.js [hunk 4]
```diff
@@ -3143,6 +3143,70 @@ describe('plot_api helpers', function () {
                 )
             ).toBe(true);
         });
+
+        it('Returns false for null values', () => {
+            expect(helpers.collectionsAreEqual(null, null)).toBe(false);
```
Comment (emilykl) [inline test/jasmine/tests/plot_api_test.js:3148]: Wouldn't it make sense for this case to return `true`?

Comment (camdecoster) [reply test/jasmine/tests/plot_api_test.js:3148]: I suppose, but that's not how the function is supposed to be used. It would require an additional branch to the conditional check and I didn't feel like adding that. If you feel strongly about it, I'll add it.

Comment (emilykl) [reply test/jasmine/tests/plot_api_test.js:3148]: Nah I don't feel strongly about it. My only suggestion would be to note these details in the function docstring.

Comment (camdecoster) [reply test/jasmine/tests/plot_api_test.js:3148]: The JSDoc param specs show the args should be an array or object. Do you think more would be necessary?

Comment (emilykl) [reply test/jasmine/tests/plot_api_test.js:3148]: Oh yeah my bad I skimmed over the jsdoc, if that conventionally means `null` is not a valid input I'm satisfied 👍
