### PR TITLE
fix for tweaking visible attribute of treemap pathbar

### LINKED ISSUE #4515: treemap pathbar visibility not reacting
In this [demo](https://codepen.io/MojtabaSamimi/pen/xxbMyrR?editors=0010) It should make `pathbar` invisible after react step 1; but it is not.

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #4515 

- [Before](https://codepen.io/MojtabaSamimi/pen/WNbPPBe?editors=1000)
- [After](https://codepen.io/MojtabaSamimi/pen/ZEYwVbR?editors=0010)

@nicolaskruchten 
@alexcjohnson 
cc: @plotly/plotly_js

### CODE REVIEW

File: src/traces/treemap/plot.js [hunk 1]
```diff
@@ -103,6 +103,10 @@ function plotOne(gd, cd, element, transitionOpts) {
         return;
     }
 
+    if(!trace.pathbar.visible) {
+        selAncestors.remove();
+    }
```
Comment (etpinard) [inline src/traces/treemap/plot.js]: It's probably cleaner to move this below from 

https://github.com/plotly/plotly.js/blob/326cb04f9f1fbf1d0f8133b8e4853ca8b2dd98ee/src/traces/treemap/plot.js#L615-L634

```js
if(trace.pathbar.visible) {
  // ...
} else {
   selAncestors.remove();
}
```

Comment (archmoj) [reply src/traces/treemap/plot.js]: Good call. Done in https://github.com/plotly/plotly.js/pull/4516/commits/838d1c39c076afca631b42fdfe208fc052fe7434.

**Comment by etpinard** [comment]
:dancer: - thanks!
