### PR TITLE
Fix event data and some hover templates for x/y/z heatmap + contour

### LINKED ISSUE #4260: customdata not working in x/y/z heatmap
in both `hovertemplate` and hover data.

See https://codepen.io/etpinard/pen/bGGNXoz?editors=1010

### PR DESCRIPTION
**Pull request by etpinard**
fixes #4260

before: https://codepen.io/etpinard/pen/bGGNXoz?editors=1010
after: https://codepen.io/etpinard/pen/ExaQOBe?editors=1010

cc @archmoj

### CODE REVIEW

File: test/jasmine/tests/contour_test.js [hunk 1]
```diff
@@ -648,4 +655,29 @@ describe('contour hover', function() {
...
+                z: [10, 4, 20],
+                text: ['a', 'b', 'c'],
+                hoverinfo: 'text'
+            }])
+            .then(done);
+        });
+
+        afterAll(destroyGraphDiv);
+
+        it('should find closest point and should', function() {
```
Comment (archmoj) [inline test/jasmine/tests/contour_test.js]: Something is missing after "and should"?

Comment (etpinard) [reply test/jasmine/tests/contour_test.js]: ...

https://github.com/plotly/plotly.js/blob/771e279736ae095aa8d7ff11a9170d76cdd779ec/test/jasmine/tests/contour_test.js#L679

---

When a test fails, this reads as "should find closest point and should have correct index".

**Comment by archmoj** [comment]
@etpinard 
Thanks very much for the bug fix and codepens.
:dancer:
